In [13]:
# Add the Pandas dependency.
import pandas as pd

# Files to load
#school_data_to_load = "Resources/schools_complete.csv"
#student_data_to_load = "Resources/students_complete.csv"

#or
import os
school_data_to_load = os.path.join(os.path.dirname(""), "Resources", "schools_complete.csv")
student_data_to_load = os.path.join(os.path.dirname(""), "Resources","students_complete.csv")

In [14]:
# Read the school data file and store it in a Pandas DataFrame.

print(school_data_to_load)

school_data_df = pd.read_csv(school_data_to_load)

student_data_df = pd.read_csv(student_data_to_load)
# Determine if there are any missing values in the school data.
school_data_df.count()

Resources\schools_complete.csv

School ID      15
school_name    15
type           15
size           15
budget         15
dtype: int64

In [15]:
# Determine if there are any missing values in the school data.
school_data_df.isnull()

    School ID  school_name   type   size  budget
0       False        False  False  False   False
1       False        False  False  False   False
2       False        False  False  False   False
3       False        False  False  False   False
4       False        False  False  False   False
5       False        False  False  False   False
6       False        False  False  False   False
7       False        False  False  False   False
8       False        False  False  False   False
9       False        False  False  False   False
10      False        False  False  False   False
11      False        False  False  False   False
12      False        False  False  False   False
13      False        False  False  False   False
14      False        False  False  False   False

In [16]:
# Determine if there are any missing values in the student data.
student_data_df.notnull().sum()

Student ID       39170
student_name     39170
gender           39170
grade            39170
school_name      39170
reading_score    39170
math_score       39170
dtype: int64

In [17]:
# Determine data types for the school DataFrame.
school_data_df.dtypes

school_data_df.dtypes

School ID       int64
school_name    object
type           object
size            int64
budget          int64
dtype: object

In [18]:
# Put the student names in a list.
student_names = student_data_df["student_name"].tolist()
student_names

['Paul Bradley',
 'Victor Smith',
 'Kevin Rodriguez',
 'Dr. Richard Scott',
 'Bonnie Ray',
 'Bryan Miranda',
 'Sheena Carter',
 'Nicole Baker',
 'Michael Roth',
 'Matthew Greene',
 'Andrew Alexander',
 'Daniel Cooper',
 'Brittney Walker',
 'William Long',
 'Tammy Hebert',
 'Dr. Jordan Carson',
 'Donald Zamora',
 'Kimberly Santiago',
 'Kevin Stevens',
 'Brandi Lyons',
 'Lisa Davis',
 'Kristen Lopez',
 'Kimberly Stewart',
 'Christopher Parker',
 'Chelsea Griffith',
 'Cesar Morris',
 'Melanie Decker',
 'Tracey Oconnor',
 'Kelly James',
 'Nicole Brown',
 'Bobby Harris',
 'Brian Fernandez',
 'Candace Phelps',
 'Amy Gonzalez',
 'Steven Green',
 'Benjamin Carlson',
 'Kevin Bailey',
 'Jesse Newton',
 'Kimberly Mercado',
 'Gregory Roberts',
 'Matthew Mayer',
 'Jennifer Parks',
 'John Carlson',
 'Megan Roberts',
 'Debra Flores',
 'Heidi Jackson',
 'Denise Bradford',
 'Ellen Brown',
 'Amy Perkins',
 'Natalie Mitchell',
 'Tiffany Gutierrez',
 'Jennifer Hess',
 'Christine Fletcher',
 'Jon Smith',
 'Tracey Yates',
 'Jerry Gordon',
 'Michael Cox',
 'Madeline Snyder MD',
 'Allison King',
 'Theresa Meyer',
 'Jared Wood',
 'Eric Maynard',
 'Mark Owens',
 'Ronnie Conley',
 'Kimberly Davis',
 'Amy Mitchell',
 'Mr. Dylan Taylor MD',
 'Elizabeth Henderson',
 'James Lopez',
 'Michael Morgan',
 'Angela Francis',
 'Breanna Taylor',
 'Jason Johnson',
 'Kyle Martin',
 'Dr. Scott Gill',
 'Lisa Long',
 'Erin Liu',
 'Marcus Richards',
 'Jason Thompson',
 'Elizabeth Mckinney',
 'Jessica Bailey',
 'Lisa Frye',
 'Lindsey Baker',
 'Lisa Ramirez',
 'Joseph Butler',
 'Tina Lynch',
 'Leah Benitez',
 'Elizabeth Parker',
 'Melissa Hunter',
 'Miss Madison Everett',
 'Ronald Garcia',
 'Mark Cherry',
 'Ryan Stokes',
 'Isaiah Maldonado',
 'Micheal Dennis',
 'Kevin Martinez',
 'Jessica Smith',
 'Dawn Trujillo',
 'Virginia Ramirez MD',
 'Marc Hernandez',
 'Jose Gonzalez',
 'Jason Dennis',
 'Gary Morris',
 'William Mcdonald',
 'Michael Savage',
 'Alexis Todd',
 'David Hansen',
 'Steven Mendez',
 'Ryan Lynch',
 'Timothy Marks',
 'Alexander Johns',
 'Kenneth Chavez',
 'Dennis Williams',
 'Michael Roy',
 'Richard Ryan',
 'Matthew Reyes',
 'Stephanie Ward',
 'Christopher Tucker',
 'Daniel Jones',
 'Devin Craig',
 'Erin Prince',
 'Bernard Ortiz',
 'Nicole Miller',
 'Christopher Fritz',
 'Bonnie Mckinney',
 'Troy Nelson',
 'Jennifer Lee',
 'Ronald Ward',
 'Nathaniel Hampton',
 'Michael Travis',
 'James Taylor',
 'Thomas Strickland',
 'Brittany Jackson',
 'Marisa Lowe',
 'Nicole Thomas',
 'Matthew Rodriguez',
 'Kent Fernandez',
 'Michelle Martin',
 'John Sparks',
 'Ann Blake',
 'Melissa Miller',
 'Steven Houston',
 'Kristen Anderson',
 'Cory Jones',
 'Jennifer Mora',
 'Dennis Griffin',
 'Darryl Brown',
 'Martin Mosley',
 'Joyce Diaz',
 'Jeffrey Rose',
 'Jamie Moreno',
 'Catherine Williams',
 'Lauren Byrd',
 'Vanessa Frazier',
 'Stephen Bryant',
 'Lawrence Liu',
 'Joseph Larsen',
 'Susan Collier',
 'Meagan Jensen',
 'Julie Harper',
 'Meghan Carroll',
 'Wanda Horton',
 'Mary Campbell',
 'Jennifer Rodgers',
 'Heather Cooper',
 'Ryan Perez',
 'Ryan Cox',
 'Darren Zavala',
 'Joseph Morales III',
 'Aaron West',
 'James Combs',
 'Curtis Garner',
 'Sarah Miller',
 'Samantha Thomas',
 'Robert Atkins',
 'Alexis Crawford',
 'Ryan Maddox',
 'Jonathan Meyer',
 'Donna Wagner',
 'William Kennedy',
 'Kimberly Martinez',
 'Matthew Anderson',
 'Kari Miller',
 'Jenna Luna',
 'Justin Contreras',
 'Mary Fox',
 'Joseph Perkins',
 'Kelly Phillips',
 'Justin Thornton',
 'Joshua Barber',
 'Travis Jackson',
 'Jordan Beasley',
 'Kevin Allen',
 'Victoria Harris',
 'Victoria Joseph',
 'Brandy Marshall',
 'Ryan Jimenez',
 'Michael Chan',
 'Christopher Phillips',
 'Kevin Murphy',
 'Vanessa Harper',
 'James Ferguson',
 'Carol Schroeder',
 'Jerry Phillips',
 'Kristin Wade',
 'Jessica Warner',
 'Dorothy Burke',
 'Bethany Walter',
 'Melissa Avery',
 'Daniel Sutton',
 'Ryan Johnson',
 'Timothy Quinn',
 'Zachary Allen',
 'Lauren Schmitt',
 'Stephanie Armstrong',
 'Ruben Rivera',
 'Patricia Petty',
 'Joseph Jacobs',
 'Bianca Wilson',
 'Donald Perez',
 'Curtis Gomez',
 'Courtney Brown',
 'Nicole Randall',
 'Steven Lambert',
 'Anthony Alvarez',
 'Shawn Farrell',
 'Jesus Schmidt',
 'Laura Wright',
 'Steven Smith',
 'Norman Thompson',
 'Anthony Wright',
 'Kayla Watts',
 'Aimee Johnson',
 'Heidi Scott',
 'Anthony Williams',
 'Sarah Hill',
 'Kim Wang',
 'Beth Manning',
 'Ryan Hanson',
 'James Wood',
 'Corey Greene',
 'John Carter',
 'Beth Garza',
 'Karen Jones',
 'Stephanie Poole',
 'Lisa Brown',
 'Paul Scott',
 'Evelyn Buck',
 'Terry Harrell',
 'Leah Skinner',
 'Anthony Mercado',
 'Walter Kelly',
 'Lori Evans',
 'Ashley Jones',
 'Amber Soto',
 'Patrick Phillips',
 'Linda Curry',
 'Alexander Obrien',
 'Vincent Garza',
 'Terry Marsh',
 'Angela Perkins DVM',
 'Peter Hampton',
 'David Cross',
 'Clinton Ortega',
 'Jamie Escobar',
 'Sandra Mason',
 'Craig Cole',
 'Lisa Warren',
 'Maria Howard',
 'Michael Porter',
 'John Turner',
 'Timothy Wang',
 'Amanda Taylor',
 'Karen Mckenzie',
 'Brandon Miles',
 'Christina Whitaker',
 'Nicole Peterson',
 'Ashley Moore',
 'Todd Carrillo',
 'Robert Williams',
 'Ashley Jones',
 'Vanessa Parker',
 'Robert Carlson',
 'Jared Lewis',
 'Christopher Hernandez',
 'Kimberly Harris',
 'Katrina Hill',
 'Heather Lee',
 'Donald Harmon',
 'Elizabeth Sanders',
 'Richard Ramsey',
 'Carmen Johnson',
 'Elaine Osborne',
 'Kent Burns',
 'Meagan Smith',
 'Craig Hahn',
 'Jeremy Wu',
 'Aaron Rodriguez',
 'Matthew Taylor',
 'Diana Evans',
 'Michele Pearson',
 'Erik Wagner',
 'Maria Welch',
 'Debra Martin',
 'Devon Conner',
 'Christine Patel',
 'David Lopez',
 'Nathan Baird',
 'Samuel Castillo',
 'Rebecca Payne',
 'Carl Johnson',
 'William Adams',
 'Paula Harrison',
 'Wayne Atkinson',
 'Lindsay Frank',
 'Jose Garcia',
 'Andrew Gaines',
 'Rachael Liu',
 'Donald Lewis',
 'Shane Edwards',
 'Todd Levy',
 'Joanna Moore',
 'Michael Lewis',
 'James Robinson',
 'Jeffrey Arellano',
 'Heather Allen MD',
 'Lori Villarreal',
 'Robert Harper',
 'Karen Villegas',
 'Tracey Crane',
 'Elizabeth Allen',
 'Jorge Lynn',
 'Harold Gordon',
 'Nicholas Mcclain',
 'Tanya Harris',
 'Amy Smith',
 'Kathy Morse',
 'Andrea Wood',
 'Maureen Massey',
 'Daniel Smith',
 'Alexandra Smith',
 'Caitlin Hall',
 'Jose Carlson',
 'Deborah Macias',
 'Dwayne Rice',
 'Matthew Harris',
 'Eric Bowman',
 'Samuel Ali',
 'David Miller',
 'James Moreno',
 'Brooke Austin',
 'Alisha Martin',
 'Neil Rodriguez',
 'Gary Williams',
 'Michael Pittman',
 'Stephanie Palmer',
 'Christine Perry',
 'Suzanne David',
 'Amber Smith',
 'Ryan Jones',
 'Emily Ford',
 'Kelsey Shea',
 'Katherine Wallace',
 'Erica Conway',
 'Tyler Parker',
 'Michael Parks',
 'Elizabeth Hunt',
 'Grant Jackson',
 'Daniel Matthews',
 'Diana Silva',
 'Frank Garza',
 'Terri Fischer',
 'Robert Goodwin',
 'Bobby Ruiz',
 'Stephanie Taylor',
 'Erin Hill',
 'Erin Cohen',
 'Jeffrey Morris',
 'Elizabeth Simpson',
 'Jennifer Davis',
 'Rachel Burton',
 'Joseph Wilkins',
 'Lawrence Montgomery',
 'Patricia Howard',
 'Jessica Hanson',
 'Donna Dean',
 'Edwin Reid',
 'Jodi Brown',
 'Elizabeth Richard',
 'Aaron Martinez',
 'Stephen Fischer',
 'Diana Reeves',
 'Jeffrey Eaton',
 'Evelyn Miller',
 'Christopher Kidd',
 'Sarah Adams',
 'Melinda Nelson',
 'Kevin Brooks',
 'John Bowen',
 'Tracie Abbott',
 'Allen Foster',
 'Kathryn Elliott',
 'Christopher Walker',
 'Cynthia Martin',
 'Amanda Bennett',
 'Dennis Padilla',
 'Antonio Miller',
 'Melissa Trevino',
 'Andrew King',
 'John Martinez',
 'Lauren King',
 'Stephanie Mercado',
 'William Smith',
 'Jonathan Marshall',
 'Luke Lowery MD',
 'Emily Reynolds',
 'Kevin Mclean',
 'Elizabeth Taylor',
 'Pamela Rivas',
 'Tammy Martin',
 'Holly Watkins',
 'Patrick Chen',
 'Michelle Griffin',
 'Theresa Andrews',
 'Alan Henry',
 'Dr. Larry Hines',
 'Travis Frazier',
 'Julie Jones',
 'Natalie Reynolds',
 'Jessica Cohen',
 'Jason Robinson',
 'Heather Palmer',
 'Emily Cardenas MD',
 'Scott Glover',
 'Jacqueline White',
 'Mrs. Elizabeth Espinoza DDS',
 'Toni Porter',
 'Jennifer Mejia',
 'Brenda Peterson',
 'Paul Hamilton',
 'Patricia Nguyen',
 'James Ho',
 'Elizabeth Cohen',
 'Stephanie Lane',
 'Dawn Rhodes',
 'Theresa Robinson',
 'Breanna Mosley',
 'Carmen Wilson',
 'Ian Brown',
 'Kathleen Matthews',
 'Bryan Diaz',
 'Gina Sweeney',
 'Alan Garcia',
 'Erik Wheeler',
 'Stephanie Robles',
 'Samantha Hanson',
 'Christopher Williams',
 'Stephanie Hart',
 'Mrs. Lisa Becker',
 'Bianca Johnson',
 'Amy Steele',
 'Gina Contreras',
 'Jaime Alexander',
 'Kevin Coleman',
 'Caitlin Williams',
 'Joseph Lloyd',
 'Carrie Hernandez',
 'Mr. Travis Young',
 'Francis Wright',
 'Joel Harper',
 'Eduardo Park',
 'Melissa Yoder',
 'Donna Campbell',
 'Connie Delacruz',
 'Luis Parker',
 'Pamela Watts',
 'Lindsey Mitchell',
 'Brenda Price',
 'Joseph Howard',
 'Amy Evans',
 'Paula Fernandez DVM',
 'Amber Cunningham',
 'Preston Wheeler',
 'James Lopez',
 'Chad Drake',
 'Samuel Blackburn',
 'Shawn Nielsen',
 'Eric Perez',
 'Kevin Montgomery',
 'Terry Thomas',
 'Kim Meyer',
 'Michael Townsend',
 'Ronnie Rodriguez',
 'Savannah Smith',
 'Shane Nguyen',
 'Michael Brown',
 'Robert Young',
 'Daniel Griffin',
 'James Johnson',
 'Mary Cox',
 'Tina Aguirre',
 'Jillian Mcdonald',
 'Matthew Branch',
 'Christopher Jordan',
 'Victor Mcguire',
 'Erin Arnold',
 'Nicholas Wu',
 'Kristen Wilson',
 'Morgan Moore',
 'Stephen Smith',
 'Jeremy Romero',
 'Julie Bush',
 'Brittany Taylor',
 'James Kim',
 'Ashley Roberts',
 'Brandon Johnson',
 'David Davenport',
 'Mark Washington',
 'Alicia Marshall',
 'Barbara Santana',
 'Samantha Parker',
 'Joseph Walters',
 'Michael Zamora',
 'Kyle Cobb',
 'Jill Clark',
 'Sarah Warren',
 'Jennifer Robinson',
 'Patricia Johnson',
 'Henry Evans',
 'Alexander Ramsey',
 'Brandon Stephens',
 'Jeff Holland',
 'Samuel Schultz',
 'Brett Johnson',
 'Daniel Sherman',
 'Justin Mccall',
 'Jonathan Evans',
 'Jacqueline Kennedy',
 'Martin Stephenson',
 'Lindsey Lane',
 'Jessica Hart',
 'Edward Lucas',
 'Lisa Osborne',
 'Hannah Black',
 'Alexander Paul',
 'Brenda Wong',
 'Thomas Delgado',
 'Jeremy Sutton',
 'Paula Donaldson',
 'Valerie Thompson',
 'John Schaefer',
 'Jesus Manning',
 'Tyrone Lawson',
 'Carl May',
 'Brittany Russell',
 'Philip Edwards',
 'Robert Aguilar',
 'Aaron Russo',
 'Tracy Andrade',
 'Amy Sullivan',
 'Howard Beck',
 'Dr. Xavier Bell II',
 'Dawn Schultz',
 'Caleb Lucas',
 'Barbara Gonzalez',
 'Charles Yang',
 'David Gallagher',
 'Bethany Vargas',
 'Jennifer Schultz',
 'Paula Marshall',
 'Jordan Elliott',
 'Samantha Mcmillan',
 'Judith Johnson',
 'Grace Palmer',
 'Brandon Ramirez',
 'Carol Smith',
 'Matthew Odom',
 'Erika Gray',
 'Donna Kramer',
 'Jonathan Snyder',
 'Frank Howe',
 'Amy Beck',
 'Lori Holmes',
 'Rebekah Hampton',
 'Perry Bishop',
 'Andrew Hanson MD',
 'Jody Hughes',
 'Anna Garcia',
 'Colleen Walker',
 'Danny Bridges',
 'Kristina Ford',
 'Sabrina Davidson',
 'Alexander Freeman',
 'Jack Davis',
 'Victor Rivera',
 'Elizabeth Pena',
 'Neil Castro',
 'Michael Briggs',
 'Anna Andersen',
 'Elizabeth Oconnor',
 'Zachary Brooks',
 'Scott Jackson',
 'Mary Fuentes',
 'Denise Reyes',
 'Janice Collier',
 'Tina Barber',
 'Keith Rojas',
 'Michelle Decker',
 'James Smith',
 'Alexandra Thompson',
 'Jacqueline Campbell',
 'Austin Clark',
 'Brooke Thomas',
 'Molly Smith',
 'Pamela Beck',
 'Timothy Morris',
 'Lauren White',
 'Jessica Beltran',
 'Alexandra Jones',
 'Evelyn Rice',
 'Stephen Ellis',
 'Caroline Smith',
 'Fred Case',
 'Crystal Anderson',
 'Jordan Gross',
 'Marie Harris',
 'Charles Hayes',
 'Beverly Sheppard',
 'Denise Solis',
 'Alexander Myers',
 'Sally Robertson',
 'Steven Morris',
 'Nina Flores',
 'Miguel Patterson',
 'John Simpson',
 'Charles Cruz',
 'Monica Davis',
 'James Fields',
 'Kevin Frederick',
 'Jeremy Soto',
 'Ronald Harris',
 'Carol Stewart',
 'Albert Durham',
 'James Sanchez',
 'John Adams',
 'Cody Williams',
 'Ernest Love',
 'Tommy Smith',
 'Jared Anderson',
 'Jennifer Yang',
 'Joe Mercado',
 'Mr. Roberto Wright MD',
 'Michael Smith',
 'William Park',
 'Benjamin Williams',
 'Dean Perez',
 'Mr. Dale Miller',
 'Marissa Russell',
 'Mary Gonzalez DDS',
 'April Jackson',
 'William Hayes',
 'Meghan Holloway',
 'Amy Coleman',
 'James Green',
 'Michael Tran',
 'Joseph Cortez',
 'Anita Moss',
 'Benjamin Stokes',
 'Michael Li',
 'Alexander Rosales',
 'Katie Dawson',
 'Shelly Erickson',
 'Kathryn Turner',
 'Jacob Lee',
 'Ryan Smith',
 'Joshua Fernandez',
 'Mia Roach',
 'William Rodriguez',
 'Wanda Cruz',
 'Pamela Hall',
 'David Smith',
 'Jason Brown',
 'Chelsea Alexander',
 'Kimberly Tate',
 'Daniel Williams',
 'Terri Jacobson',
 'Paul Harris',
 'Jessica Thompson',
 'Nancy Hawkins',
 'Deborah Phillips',
 'Mark Mendoza',
 'Stephen Williamson',
 'Jennifer Strong',
 'Matthew Moore',
 'Raymond Parker',
 'Lee Evans',
 'Curtis Rodriguez',
 'Sara Morris',
 'Dawn Palmer',
 'Brianna Benson',
 'Luis Watts',
 'Mrs. Cindy Brown',
 'Summer Sandoval',
 'Ashley Smith',
 'Randy Wallace',
 'Angela Simmons',
 'Sandra Haley',
 'George Morgan',
 'Melissa Ali',
 'Matthew Oliver',
 'Michael Kirk',
 'Terry Khan',
 'Kristie Elliott',
 'Joel Campbell',
 'Anthony Henderson',
 'Brent Christensen',
 'Heidi Hayes',
 'Ryan Mcbride',
 'Kyle Murillo',
 'Angela Powell',
 'Jeanette Simmons',
 'Adam Vance',
 'Kristen Murray',
 'Jessica Burnett',
 'Alex Walker',
 'Robert Phillips',
 'Elizabeth Martinez',
 'Kristina Young',
 'Sarah Morgan',
 'Cheryl Harding',
 'Keith Hunter',
 'Todd Williams',
 'James White MD',
 'Kyle Johnson',
 'Andrea Suarez',
 'Michael Sanchez',
 'Jaime Torres',
 'Donald Gill DDS',
 'Austin Lee',
 'Adrian Bowman',
 'Julie Perez',
 'Debra Maxwell',
 'Bradley Phillips',
 'Sonya Simmons',
 'Eric Miller',
 'Charles Berger',
 'Mary Monroe',
 'Destiny Burns',
 'Patrick Khan',
 'Nathaniel Henson',
 'Larry Miller',
 'Timothy French',
 'Xavier Mitchell',
 'Jason Crosby',
 'Joshua Johnson',
 'Alyssa Clark',
 'Jonathan Cooper',
 'Mark Hunt',
 'Norman Moore',
 'Brian Atkins',
 'Zachary Jones',
 'Danielle Wong',
 'Patricia Lane',
 'Joshua Rose',
 'Hannah Montes',
 'Mrs. Catherine Williams MD',
 'Michael Jenkins',
 'James Scott',
 'Evan Ballard',
 'Andrea Miller',
 'Jasmine Lynch',
 'Jennifer Fox',
 'Jared Castro',
 'Eugene Cox',
 'Wendy Wilson',
 'Debbie Smith',
 'Michael Fletcher',
 'Jay Waters',
 'Melissa Martinez',
 'Cory Howard',
 'Mitchell Hanson',
 'Corey Boyer',
 'Elizabeth Gonzalez',
 'Robert Hutchinson',
 'David Hernandez',
 'Tammy Jordan',
 'Denise Johnson',
 'Brandi Copeland',
 'Evan Marshall',
 'Gregory Long',
 'Kristen Underwood',
 'Walter French',
 'Edwin Thompson',
 'Edward Rivera',
 'Brandon Wilson',
 'Alejandra Todd',
 'Dana Hoffman',
 'David Howard',
 'Ashley Caldwell MD',
 'Cindy Horn',
 'Kevin Armstrong',
 'Stacey Porter',
 'Patrick Hunt',
 'David White',
 'Tammy Black',
 'Joanna Williams',
 'Becky Moran',
 'Brenda Smith',
 'Gabrielle Webb',
 'Mr. Jared Campbell',
 'Ryan Jenkins',
 'Thomas Shepard',
 'Jeremiah Boyd',
 'Matthew White',
 'Christina Anderson',
 'Edward Olson',
 'Emily Bryant',
 'Amy Guzman',
 'Kathleen Owens',
 'John Davila',
 'Nicole King',
 'Jason Villarreal',
 'Matthew Washington',
 'Peter Simpson',
 'Cristian Espinoza',
 'Steven Fry',
 'David Miller',
 'Tamara Hernandez',
 'Jordan Lewis',
 'Carol Anderson',
 'Michael Moreno PhD',
 'Nicholas Logan',
 'Paul Anderson',
 'Jason Young',
 'Wesley Martin',
 'Karen Wall',
 'Tara Parker MD',
 'Michael Reyes',
 'Amy Henderson',
 'Jessica Reed',
 'Joseph Miranda',
 'Mackenzie Jones',
 'Jon Espinoza',
 'Kelly Medina',
 'Jason Rubio',
 'Jennifer Munoz',
 'Christopher Warner',
 'Vincent Thomas',
 'Andrew Young',
 'David Jenkins',
 'Daniel Stephens',
 'Elizabeth Lewis',
 'Aaron Moore',
 'Lisa Hogan',
 'Shawn Williams DVM',
 'Michele Dickerson',
 'Dr. Alicia Martinez',
 'Mr. Timothy Anderson',
 'Sierra Jackson',
 'Sharon Taylor',
 'Jeffrey Smith',
 'Mark Taylor',
 'Christina Ross',
 'Judy Hall',
 'Jennifer Fox',
 'Kenneth Moran',
 'Gerald Ferguson',
 'Albert Carter',
 'Michael Reilly',
 'Kathleen Schwartz',
 'Stacey Harris',
 'Mrs. Paula Lee',
 'Adrian Black',
 'Rita Moreno',
 'Jason Perry',
 'Scott Ortiz',
 'Randy Mueller',
 'Samantha Anderson',
 'Phillip Brown',
 'Christina Kerr',
 'Derrick Hill',
 'Nathan Bond',
 'Marie Wilson',
 'Caitlin Jones',
 'Barbara Campbell',
 'Katie Gonzales',
 'Mr. Elijah Hall',
 'James Sanders',
 'Nicholas Martinez',
 'Maria Mack',
 'Mary Mason',
 'Tiffany Campbell',
 'Mr. Raymond Stone',
 'Dominique Henderson',
 'Martin Williams',
 'Hannah Parker',
 'Susan Webb',
 'Rachel Johnson',
 'Darren Davis',
 'Tim Carr',
 'Jesus Ryan',
 'John Hays',
 'Scott Stewart',
 'Alexandra Roberts',
 'Amanda Norman',
 'James Moody',
 'Brenda Jones',
 'Kathy Smith',
 'Raymond Clark',
 'Ashley Martin',
 'Tamara Flowers',
 'Cesar Hanson',
 'Ross Strickland',
 'Randy Moore',
 'Henry Andersen',
 'Paul Martin',
 'Sarah Stanley',
 'Jordan Lewis',
 'Ashley Richardson',
 'Michael Brown',
 'Jason Davis',
 'Wendy Mcclain',
 'Troy Williams',
 'Carrie Alexander',
 'Kyle Ware',
 'Michael Robinson',
 'Roger Wilson',
 'Teresa Fuller',
 'Craig Silva',
 'Duane Thomas',
 'Jon Crosby',
 'Jon Steele',
 'Daniel Shaw',
 'Gwendolyn Williams',
 'Angela Hess',
 'Cameron Arnold',
 'Janice Garcia',
 'Anne Bullock',
 'Katie Moody',
 'Kayla Rivas',
 'Danny Pearson',
 'Billy Robles',
 'Michelle Delgado',
 'Cindy Harrison',
 'John Dickerson MD',
 'Tina Armstrong',
 'Mr. Alex Franklin',
 'Ryan King',
 'Christine Guzman',
 'Helen Malone',
 'Benjamin Carpenter',
 'Mrs. Jessica Dunn',
 'Jessica Kaiser',
 'Brandon Black',
 'David Hernandez',
 'Brenda Turner',
 'Katherine Black',
 'Larry Santos',
 'Zachary Dominguez',
 'Tanya Fernandez',
 'Joseph Nichols',
 'Rebecca Martinez',
 'Traci Ramirez',
 'Ryan Bauer',
 'Joshua Williams',
 'Devon Foley',
 'Heidi Walter',
 'Mario Nguyen',
 'Jordan Hernandez',
 'William Miller',
 'Nicholas Chung',
 'Christine Cooley',
 'Carrie Nelson',
 'Crystal Fowler',
 'Lori Taylor',
 'Mr. Michael Stevenson',
 'Matthew Holmes',
 'David Walls',
 'Megan Martin',
 'Karen Peterson',
 'Kristen Wallace',
 'Mark Peterson',
 'Jason Jones DDS',
 'Keith Barber',
 'Patrick Green',
 'Antonio Lopez',
 'Travis Peterson',
 'Gabriel Hunter',
 'Amanda Ross',
 'Samuel Thompson',
 'Robert Bowman',
 'Cynthia Cox',
 'Brittany Miller',
 'Eric Torres',
 'Sandra Calhoun',
 'Jacob Bailey',
 'Jessica Harris',
 'Molly Carr',
 'Keith Davis',
 'Adriana Wade MD',
 ...]

In [19]:
# Create a new list and use it for the for loop to iterate through the list.
students_to_fix = []

# Use an if statement to check the length of the name.
# If the name is greater than or equal to "3", add the name to the list.

for name in student_names:
    if len(name.split()) >= 3:
        students_to_fix.append(name)

# Get the length of the students whose names are greater than or equal to "3".
len(students_to_fix)

1531

In [20]:
print(students_to_fix)

['Dr. Richard Scott', 'Dr. Jordan Carson', 'Madeline Snyder MD', 'Mr. Dylan Taylor MD', 'Dr. Scott Gill', 'Miss Madison Everett', 'Virginia Ramirez MD', 'Joseph Morales III', 'Angela Perkins DVM', 'Heather Allen MD', 'Luke Lowery MD', 'Dr. Larry Hines', 'Emily Cardenas MD', 'Mrs. Elizabeth Espinoza DDS', 'Mrs. Lisa Becker', 'Mr. Travis Young', 'Paula Fernandez DVM', 'Dr. Xavier Bell II', 'Andrew Hanson MD', 'Mr. Roberto Wright MD', 'Mr. Dale Miller', 'Mary Gonzalez DDS', 'Mrs. Cindy Brown', 'James White MD', 'Donald Gill DDS', 'Mrs. Catherine Williams MD', 'Ashley Caldwell MD', 'Mr. Jared Campbell', 'Michael Moreno PhD', 'Tara Parker MD', 'Shawn Williams DVM', 'Dr. Alicia Martinez', 'Mr. Timothy Anderson', 'Mrs. Paula Lee', 'Mr. Elijah Hall', 'Mr. Raymond Stone', 'John Dickerson MD', 'Mr. Alex Franklin', 'Mrs. Jessica Dunn', 'Mr. Michael Stevenson', 'Jason Jones DDS', 'Adriana Wade MD', 'Erica Hurley MD', 'Dr. Garrett Wright', 'Mr. James Allen', 'Mr. Timothy Harper MD', 'Dale Brown MD', 'Dr. Christina Moore', 'Angela Peterson MD', 'Jennifer Ferguson MD', 'Anthony Wilson DDS', 'Dr. Jessica Lopez', 'David Miller Jr.', 'Dr. John Jones', 'Ms. Samantha Brown', 'Cynthia Hansen DVM', 'Rebecca Montoya MD', 'Dr. Jacob Matthews', 'Dr. Jacob Bell', 'Mr. Bruce Thomas', 'Robert Martin MD', 'Mrs. Marcia Jones PhD', 'Reginald Garcia IV', 'Patricia Smith MD', 'Amy Dyer DDS', 'Brian Hall DDS', 'Douglas Levy DDS', 'Mr. Eric Ibarra', 'Benjamin Ramirez MD', 'Raymond Freeman DDS', 'Carla Reeves MD', 'Dr. Donald Williams', 'Mr. John Carter', 'William Jackson DVM', 'Mr. Mitchell Cooper', 'Kevin Brown IV', 'Mrs. Kathleen Reed', 'Donna Robinson MD', 'Mrs. Dawn Olson DDS', 'Mr. Dustin Glover', 'Alexis French MD', 'Lisa Guerrero MD', 'David Nguyen DVM', 'William Washington Jr.', 'Julie Patterson MD', 'Mr. James Kelly', 'Dr. Robert Martin', 'Darlene Thomas PhD', 'Mr. Juan Jenkins', 'Mr. Juan Bryant II', 'Mr. Matthew Coleman', 'Bonnie Hammond MD', 'Kathleen Harris DDS', 'Steven Velez DDS', 'Tammy Cruz DDS', 'Dr. Marie Williams', 'Kenneth Paul Jr.', 'Mr. Jose Morris', 'Scott Rivers III', 'Melissa Rodriguez MD', 'Geoffrey Ortiz MD', 'Matthew Stewart MD', 'Sandra Thompson DDS', 'Mark Myers Jr.', 'Mrs. Maria Smith DDS', 'Dr. Kimberly Clements', 'Dr. Kenneth Webb', 'Amanda Patterson DVM', 'Miss Tara Banks DDS', 'Nancy Brown DVM', 'Chase Boyd MD', 'Mr. James Spence', 'Miss Colleen Stewart DDS', 'Mr. Todd Greene PhD', 'Amanda Hamilton DDS', 'Mrs. Lisa Rowland', 'Mr. Eric Moon', 'Mrs. Alicia Kelly DDS', 'Mr. Michael Norton Jr.', 'Mr. James Crosby', 'Mr. Sean Pena Jr.', 'Kathy Lucero DVM', 'Dustin Ferguson DDS', 'Dr. James Patterson', 'Dr. Juan Cobb MD', 'Victoria Garcia MD', 'Michael Evans DVM', 'Miss Ebony Bell', 'Mr. Justin Mullins DDS', 'Mrs. Jill Walker', 'Mr. Eric Hicks', 'Tara Williams DVM', 'Dr. Jessica Watkins', 'Mr. Joseph Turner', 'Cody Mueller Jr.', 'Kiara Williams MD', 'Mathew White Jr.', 'Steve Hendricks MD', 'Mr. Victor Duarte', 'Dr. Stacy Maynard', 'Mr. Steven Snyder PhD', 'Jessica Warner PhD', 'Trevor Summers DDS', 'Maria Doyle MD', 'Stacie Walker DDS', 'Megan House DVM', 'Ms. Deborah Coleman', 'Dr. Ryan Barker', 'Mr. Michael Cox', 'Mrs. Rebecca Martin DVM', 'Sara Jacobs MD', 'Mr. Jason Daugherty Jr.', 'Mrs. Natalie Holder MD', 'Charles Hernandez DDS', 'Dr. Charles Lawrence', 'Mr. Tyler Walker', 'Janet Whitaker MD', 'Jeremy Watkins MD', 'David Martinez DDS', 'Kimberly Olsen DDS', 'Dr. Nicole Roy', 'Mr. Justin Maxwell', 'Danielle Robinson DDS', 'Mrs. Susan Chase DDS', 'Mr. Alex Gonzales DDS', 'Leonard Webster II', 'David Taylor PhD', 'Mr. Christopher Stuart', 'Mr. Kevin Wilson', 'Mr. John Walters', 'Breanna Peterson MD', 'Terri Quinn PhD', 'Christian Reynolds DDS', 'Mr. Donald Gray', 'Dr. Shawn Brown', 'Samantha Salas MD', 'Valerie Thomas DDS', 'Mrs. Gina Anderson', 'Michael Stein Jr.', 'Mr. Robert Day', 'Justin Hernandez DDS', 'Mrs. Mikayla White', 'Dr. Edward Palmer', 'Elizabeth Coleman MD', 'Alexandra Hood PhD', 'Michael Gonzalez DDS', 'Ryan Phillips Jr.', 'Ashley Jones DDS', 'Susan Trujillo MD', 'Carol Baker MD', 'Kelly Ibarra MD', 'Mrs. Crystal Perez', 'Mr. Joshua Jensen MD', 'Ms. Vanessa Ortiz DDS', 'Mr. Jay Navarro', 'Dr. Jimmy Smith MD', 'John Compton DDS', 'Mario Wheeler PhD', 'Mr. Joshua Simon', 'Alicia Ferguson DVM', 'Dr. Amy Melendez', 'Gloria Fritz DDS', 'Dr. Michael Miller', 'Mrs. Alexandra Taylor', 'Dr. Jennifer Ramirez MD', 'Mrs. Amy Walker MD', 'David Dickson MD', 'Amanda Mills DDS', 'Mr. Jason West', 'Mr. Joshua Hall', 'Mrs. Elizabeth Mitchell', 'Dr. Sarah Miller', 'Allen Snyder Jr.', 'Calvin Williams Jr.', 'Dr. Tammy Shelton', 'Miss Jennifer Gibson', 'Miss Christy Robinson', 'Mr. Michael Rhodes', 'Deborah Huffman DDS', 'Ronald Torres Jr.', 'Mr. Oscar Bautista', 'Ellen Mcgee MD', 'Emily Andrews MD', 'Richard Williams PhD', 'Mr. Michael Baker PhD', 'Dr. Robert Taylor', 'Traci Obrien DDS', 'Robert Harris MD', 'Dr. Diana Martin', 'Logan Ward MD', 'Mrs. Janice Dixon', 'Gabriel Smith III', 'Linda Duran DVM', 'Ronald Mayer PhD', 'Mr. David Smith', 'Brian Pitts Jr.', 'Ms. Stephanie Rose', 'Mr. Richard Stephens', 'Miss Kimberly Joseph', 'Bruce Thompson II', 'Tony Adams DDS', 'Dr. Annette Collins DDS', 'Mr. Chad Hendricks', 'Lindsey Tyler DVM', 'Michael Drake MD', 'Jeremy Sanders II', 'Mr. George Goodwin MD', 'Amanda Ramirez DDS', 'Aaron Morris MD', 'Mrs. Michelle Butler', 'Mr. Robert Carson', 'Mrs. Jennifer Martin DDS', 'Miss Amber Wallace', 'Mrs. Mary Hardy', 'Jennifer Smith PhD', 'Jodi White DDS', 'Mr. Ryan Strickland', 'Mr. Michael Koch', 'Mrs. Kara Rodriguez DDS', 'Mr. Ryan Adams', 'Austin Johnson II', 'Mr. Samuel Robertson DVM', 'Benjamin Vargas DDS', 'Mrs. Wendy Thomas', 'Bryan Conway Jr.', 'Brittany Hatfield DVM', 'Mrs. Casey Hayes', 'Johnny Byrd MD', 'Nicole Burke MD', 'Brett Banks DVM', 'Mrs. Lori Johnson', 'Michael Shea MD', 'Jesse Thompson DDS', 'Brooke Simpson DVM', 'Mr. Michael Davis', 'Mr. Thomas White', 'Jessica Scott DDS', 'Mr. Michael Burton', 'Mrs. Laurie Brown', 'Dr. Cindy Logan', 'Nicholas Jones MD', 'Ronald Moore II', 'Mr. Jonathon Patrick', 'Mr. Andrew Kemp', 'Alexander Garcia PhD', 'Brett Campbell MD', 'Mrs. Paige Hall', 'Danielle Smith MD', 'Catherine Mendez MD', 'Mr. David Mcdonald', 'Mrs. Ashley Porter DDS', 'Jason Mcdowell MD', 'Mr. Martin Lozano', 'Bruce Hendrix MD', 'Pamela Cox DDS', 'Dr. Kristina Turner', 'Samantha Buchanan DDS', 'Mr. Cameron Singh', 'Mr. Steven Davis', 'Ruth Martinez MD', 'George White DDS', 'Dr. Michael Johnson', 'Joshua Garrison PhD', 'Mr. Nicholas Rodriguez DVM', 'Ms. Sarah Ray DVM', 'Natalie Rivera MD', 'Dr. Tracy Powell', 'Mr. Jason Chavez MD', 'Mrs. Leslie Mathews', 'Patrick Newman DDS', 'Mr. Michael Chapman DDS', 'Jennifer Long PhD', 'Matthew Anthony MD', 'Robert Garrison IV', 'Jamie Anderson DDS', 'William Gonzalez Jr.', 'Dr. Jennifer Weiss', 'Dr. Cynthia Torres', 'John Miranda DDS', 'Dr. Brian Matthews Jr.', 'Mr. Christopher Quinn', 'Mrs. Jacqueline Rose', 'Mrs. Angela Gray', 'Mrs. Tara Carpenter', 'Shannon Stevenson MD', 'Kaitlin Warner MD', 'Dr. Jessica Fowler MD', 'Mrs. Catherine Armstrong', 'John Mullins DDS', 'Christina Benson MD', 'Amy Martinez DVM', 'Ashley Edwards DVM', 'Melissa Herrera DDS', 'Adam Arroyo DDS', 'Dr. Amanda Cochran', 'Eric Richards Jr.', 'Mrs. Angela Martinez', 'Natalie Garcia MD', 'Mr. Dennis Duke', 'Christopher Fleming MD', 'Misty Beck DDS', 'Sharon Lloyd DDS', 'Mrs. Laura Malone MD', 'Dr. Gabriel Flores MD', 'Dr. Russell Gallegos', 'Kyle Walker MD', 'Caleb Oliver MD', 'Mr. Cameron Erickson', 'Pamela Oliver DVM', 'Mariah Russell MD', 'Jonathan Fisher DVM', 'Ms. Sarah Mcintosh DVM', 'Lynn Jones MD', 'Allison Martinez DDS', 'Jeffrey Zamora MD', 'Kenneth Munoz Jr.', 'Dr. Ellen Mcclure DDS', 'Samantha Ballard MD', 'Mariah Franco MD', 'Mr. Daniel Smith DVM', 'Jon Delgado Jr.', 'Mrs. Anna Dickerson', 'Mrs. Cynthia Martinez DDS', 'Angela Hamilton MD', 'Mrs. Stephanie Stone', 'Dr. Marcus Kim MD', 'Jordan Brewer PhD', 'Mrs. Veronica Neal', 'Dr. Mike Alvarez', 'Patricia Lee DDS', 'Andrew English Jr.', 'Dr. Jennifer Martinez MD', 'Dr. Donna Humphrey', 'Mrs. Jennifer Tucker DDS', 'Mrs. Jamie Bond', 'Judy Mills MD', 'Christina Jackson DDS', 'Mr. Raymond Cox Jr.', 'Dr. Donna Cooper', 'Jeffrey Mcclain Jr.', 'Mr. Joseph Hill', 'Bryan Shaffer DVM', 'Julie Bond MD', 'Michael Hunter DDS', 'Melissa Rodriguez PhD', 'Deborah Rodriguez MD', 'Mrs. Andrea Wilson', 'Dr. Jonathan Woods PhD', 'Jacob Ballard MD', 'Mr. Brian Poole V', 'Jeffrey Kim II', 'Mr. Michael Gonzalez', 'Kevin Brooks MD', 'April Hansen PhD', 'Mr. Brian Austin', 'Sara Cooper DVM', 'Kelsey Ellis MD', 'Deborah Madden MD', 'Dr. Brooke Silva', 'Dr. Melissa Allen PhD', 'Karen Thomas MD', 'Mrs. Sophia Harper', 'Tara Singleton MD', 'Dr. Alison Flores', 'Kenneth Adams MD', 'Mrs. Natasha White', 'Amanda Sanchez DDS', 'Scott Campbell DVM', 'Matthew Alexander Jr.', 'Dr. Shane Gilmore MD', 'Miss Paula Lawson', 'Mrs. Theresa Roberts', 'Kevin Reynolds Jr.', 'Mr. David Anderson', 'Dr. Gabrielle Morris', 'Jacob Skinner Jr.', 'Miss Lisa Kennedy', 'Timothy Byrd DDS', 'Haley Jordan PhD', 'Deborah Mack DVM', 'Mckenzie Morris DVM', 'Megan Saunders MD', 'Tina Meyer MD', 'Harold Sutton MD', 'James Allen DVM', 'Dr. Lauren Perry', 'Eric Riley MD', 'Jamie Rogers DDS', 'Natasha Lee MD', 'Ms. Paula Taylor', 'Theodore Mendez DDS', 'Ms. Rebecca Johnson', 'Mr. Dennis Gibson Jr.', 'Mrs. Sherry Flores MD', 'Dr. Alejandro Swanson', 'Dr. Tiffany Peters DDS', 'Christopher Crawford DDS', 'Jimmy Shea Jr.', 'Mr. Joshua Cunningham', 'Mr. Travis Jackson', 'Dr. Mary Johnson', 'Mr. Patrick Duarte', 'Mr. Adam Hernandez', 'Dr. Susan Wright', 'Miss Stephanie Perry DVM', 'Dr. Tracey Gonzalez', 'Paul Hernandez DVM', 'Mrs. Jasmine Schroeder', 'Mr. Adam Sosa', 'Linda Sanchez DDS', 'Mrs. Danielle Jones', 'Benjamin Henry MD', 'Mr. Randy Reyes', 'Mr. Russell Elliott', 'Mr. Thomas Smith MD', 'Rachel Hanna DVM', 'Robert Stephens MD', 'Dr. Sean Duncan MD', 'Maria Adams MD', 'Mrs. Theresa Bauer', 'Teresa Blair DDS', 'Dr. Jennifer Campbell MD', 'Dr. Melody Garcia', 'James Reed Jr.', 'Elizabeth Wallace MD', 'Mrs. Gina Williams', 'Emily Price MD', 'Mrs. Bonnie Boyd PhD', 'Dr. Harry Campbell', 'Dr. Kevin Simon', 'Dr. Eric Lambert PhD', 'Mr. John Mathis', 'Jason Bush DDS', 'Ms. Amy House', 'Dr. Kevin Diaz', 'Mr. Kevin Benjamin', 'Mrs. Michelle Dickerson DDS', 'Dr. Alexandra Mays', 'Mrs. Jessica Hebert', 'Dr. George Cline', 'Mrs. Whitney Scott', 'Jennifer Jenkins DDS', 'Mr. Gregg Rosario', 'Scott Roth MD', 'Evelyn Kirby MD', 'Miranda Thompson PhD', 'Dr. Carla Ross', 'Mrs. Tanya Odom', 'Jeffery Baker Jr.', 'Mrs. Melissa Medina', 'Daniel Lara MD', 'Mrs. Nicole Vazquez', 'Dr. Emily Gutierrez DDS', 'Dr. Stephanie Smith', 'Derrick Hughes III', 'Mr. Eduardo James', 'Mr. Michael Cook', 'Mr. David Hill', 'Dr. Ryan Orozco DVM', 'Joshua Rivera Jr.', 'Marc Harmon DDS', 'Mr. Keith Peters DDS', 'Amanda Freeman MD', 'Dr. Michelle Carlson', 'Dr. Stephen Vargas', 'Colleen Frederick DVM', 'Dr. Harry Chang', 'Taylor Grant MD', 'Mrs. Renee Thomas DDS', 'Dr. Shannon Johnson MD', 'Mrs. Christina Horne', 'Mrs. Deborah Walters PhD', 'Mr. Jesse Gonzalez', 'Larry Martinez DDS', 'Mrs. Anita Lee', 'Dr. James Jones', 'Dr. Tammy Jones', 'Michael Golden MD', 'Dr. Gavin Tate', 'Dr. Christopher Collins', 'Timothy Guzman Jr.', 'Mr. Alexander Thomas', 'Dr. James Lewis', 'Mr. Andrew Miller', 'Mrs. Kelly Hall', 'Dr. Kayla Lowe', 'Dr. Joseph Park', 'Dr. Alfred Foster', 'Amy Stephenson MD', 'Stephen Black DVM', 'Dr. Daryl Smith', 'Stuart Gross DDS', 'Michael Hardy DDS', 'Mr. Kenneth Chase', 'Mrs. Anna Everett MD', 'Mr. Joshua Young', 'Mrs. Robin Lopez MD', 'Dr. Elizabeth Benson', 'Dr. Casey Hogan', 'Elizabeth Peterson DVM', 'Marilyn Vasquez DVM', 'Mr. Jack Reed', 'Zachary Shields DVM', 'Mrs. Molly Lopez MD', 'Dr. Stephanie Jones', 'Benjamin George DDS', 'David Thomas DVM', 'Jill Hudson DDS', 'Mary Mccormick MD', 'Michelle Smith MD', 'Carl Burns MD', 'Mr. Juan Buckley DDS', 'Dr. Michelle Brown', 'Jose Huffman PhD', 'Deanna Mccarthy DDS', 'Mrs. Robin Hughes', 'Laura Shannon DVM', 'Mary Fox DDS', 'Ms. Jamie Sanchez', 'Meredith Tucker DVM', 'Jose Manning DDS', 'Lisa Bruce DVM', 'Crystal Howard DVM', 'Mrs. Tracy Williams', 'Mr. Jeffery Diaz', 'Julie Baker DDS', 'Miss Danielle Adams', 'Lonnie Allen II', 'Mr. Bryan Brooks', 'Ashley Jimenez MD', 'Tyrone Clark III', 'Eric Mullins DDS', 'Mr. Jonathan Walker', 'Patricia Villarreal DDS', 'Mrs. Megan Kaufman DVM', 'Mathew Thompson DVM', 'Mrs. Whitney Figueroa', 'Miss Debbie Chavez', 'Emma Bates MD', 'Jeffrey Nelson Jr.', 'Michael Mann II', 'Mrs. Karina Perry', 'Dr. Chelsey Williams MD', 'Jessica Sanchez PhD', 'Joseph Ellis PhD', 'Mrs. Heather Gregory', 'Mr. Steven Davies', 'Dr. Lauren Brown', 'Brett Garcia MD', 'Anthony Davis DDS', 'Anita Salazar DVM', 'Joseph Jones DVM', 'Edward Davis MD', 'Mr. Brian Abbott', 'Nicole Pennington MD', 'Kelly Doyle DVM', 'Franklin Chen DVM', 'Mr. Brandon Young', 'Nathan Welch PhD', 'Dr. Katrina Farmer', 'David Johnson Jr.', 'Timothy Chavez Jr.', 'Michele Oconnell MD', 'Elizabeth Tran MD', 'Dr. Grace Martin', 'Sarah Chaney DDS', 'Mrs. Brooke Henry DDS', 'Dr. Lisa Coleman', 'Brian Powell III', 'Logan Oconnell PhD', 'Lance Rangel Jr.', 'Dr. Nicole King', 'Mr. John Carroll', 'Mr. Anthony Mccormick', 'Samuel Ruiz MD', 'Ms. Jennifer Richard', 'Mr. Stephen Cochran', 'Gary Jarvis MD', 'Dustin Stephenson MD', 'Mr. Derrick Campbell DDS', 'Lori Brown MD', 'Mrs. Brooke Rodgers', 'Mr. David Moss', 'Mr. Joseph Knight DDS', 'Mrs. Brittany Duncan MD', 'Mrs. Jennifer Edwards DVM', 'William Cook PhD', 'Kristina White MD', 'Tonya Henry MD', 'Robert Sanders PhD', 'Noah Herrera Jr.', 'Linda Marshall MD', 'James Davis MD', 'Dawn Gilbert MD', 'Dr. Dennis Andrews', 'Mr. John Evans', 'Mr. Michael Brooks', 'Shannon Ortiz MD', 'Mrs. Brenda Bishop MD', 'Wanda Miller MD', 'Mrs. Sheila Wagner', 'Mrs. Kathleen Johnson DVM', 'Dr. Shannon Russo', 'Chad Chavez DVM', 'Mr. William Holt', 'Paul Jensen PhD', 'Cassandra Gardner DDS', 'Mrs. Susan Klein', 'Dr. Amanda Nguyen', 'Mrs. Leslie Esparza', 'Mrs. Jacqueline Simpson', 'Mrs. Tammy Crane', 'Dr. Wendy Oliver', 'Katelyn Mejia DDS', 'Dr. Miguel Rivera', 'Mrs. Nancy Landry', 'Renee Stewart MD', 'Breanna Mcintyre DDS', 'Sarah Fischer MD', 'Ronald Berry DVM', 'Mrs. Amanda Cook', 'Dr. Monica Gonzalez', 'Miss Jennifer Moore', 'Crystal Watson DVM', 'Suzanne Edwards DDS', 'Lance Brown DVM', 'Olivia Taylor DDS', 'Mrs. Lauren Lewis', 'Jillian Proctor MD', 'Yvette Jacobson MD', 'Chelsea Rhodes DVM', 'Robert Brown DVM', 'Maria Brooks DDS', 'Eric Johnson Jr.', 'Kelly Webb PhD', 'Dr. Valerie Chen', 'Mrs. Taylor Martin', 'Dr. Andre Casey', 'Mr. Stephen Clements', 'Kevin Morrow MD', 'Dr. Louis Skinner', 'Adam Walker DVM', 'Mr. Steven Smith', 'Dr. Willie King', 'Miranda Stanley DVM', 'Dr. Travis Johnson', 'Mr. Christopher Cook', 'Mr. Martin Hensley DDS', 'Kelly Haynes DVM', 'Mr. Alexander Foster MD', 'Mr. William Rodgers', 'Anne Larsen MD', 'Sherry Johnson MD', 'Victor Chavez II', 'Brandon Dougherty DDS', 'Elizabeth Young DDS', 'Mr. Joshua Lucas', 'Michael Walsh DDS', 'Mrs. Lauren Campbell', 'Troy Camacho MD', 'Richard Ellis Jr.', 'Mr. Brandon Johnson', 'Mrs. Brooke Campbell', 'Dr. Karen Kelley', 'Mr. Jason Simmons', 'Mr. Larry Francis MD', 'Mr. Christopher Griffin', 'Mr. Dean York', 'Charles Goodman Jr.', 'Miss Erin Bradley DDS', 'Mr. Michael Allen', 'Kelly Romero MD', 'Anna Yang MD', 'John White DVM', 'Mr. James Barnes', 'Mr. Carlos Warner', 'April Calderon MD', 'Mrs. Kimberly Key DDS', 'Eric Park DDS', 'Patrick Barker PhD', 'Michael Singh Jr.', 'Jonathan Smith Jr.', 'Allen Morris Jr.', 'Mr. Lee Rose', 'Dr. Carl James', 'Dr. Kimberly Benjamin', 'Mr. Lucas Smith', 'Mr. Jason Grant DDS', 'Aaron Solis Jr.', 'Ryan Graham MD', 'Justin Morgan MD', 'Mrs. Victoria Cochran', 'Dr. Ryan Roberts', 'Katie Strickland DDS', 'Emma Perry MD', 'Mr. Daniel Mckinney Jr.', 'Mr. Paul Farmer', 'Stephanie Howard MD', 'Mandy Mcconnell DDS', 'Mrs. Angelica Hall', 'Christopher Petty Jr.', 'Megan Shaw DDS', 'Bianca Huynh MD', 'Miss Christina Burns', 'Melissa Dunn MD', 'Mr. Derek Wilson', 'Mr. Angel Johnson', 'Mrs. Nicole Duran', 'Michael Garcia Jr.', 'Mrs. Bethany Fisher PhD', 'Mr. Daniel Nguyen DDS', 'Wanda Moore MD', 'Charles Short II', 'Kimberly Jacobson PhD', 'Debbie Brown DVM', 'Mr. Michael Dyer MD', 'Joshua Kim DDS', 'Daniel Fitzpatrick PhD', 'Jordan Waller MD', 'Mr. Jesse Bell', 'Mario Myers MD', 'Terry Adams DDS', 'Derek Barker Jr.', 'Mrs. Renee Gordon', 'Mr. Vincent King', 'Dr. Oscar Lawson MD', 'Lisa Zimmerman DVM', 'Mr. Phillip Vaughan', 'Joseph Dyer MD', 'Dr. Austin Cole', 'Mrs. Amanda Martin', 'John Thomas MD', 'Sierra Dominguez MD', 'Mrs. Katie Weber MD', 'Ms. Nancy Green', 'Mrs. Pamela Garcia', 'Danielle Stanton MD', 'Elizabeth Logan DDS', 'Courtney Wall DVM', 'Karen Harris PhD', 'Mrs. Amanda Herring', 'Dr. David Miller', 'Mr. Eric Anderson', 'Mrs. Sheena Bailey DVM', 'Zachary Garrett III', 'Thomas Harrison Jr.', 'Megan Bennett DVM', 'Mr. Steven Harrison', 'Amy Mcintosh MD', 'Dr. Frank Anderson', 'Jamie Dawson MD', 'Mr. Andrew Mitchell V', 'Dr. Travis Richmond', 'Mrs. Amy Cain', 'Aaron Davis Jr.', 'Thomas Burgess MD', 'Amanda Hale DVM', 'Derek Cooke MD', 'Dr. Daniel Bowman', 'Dr. Jonathan Palmer', 'Lori Mitchell DDS', 'Mr. Richard Armstrong', 'Dr. Timothy Johnson', 'Mrs. Pam Lewis DVM', 'Amy Gutierrez DDS', 'Dr. Christina Flores', 'Brian Bailey Jr.', 'Mrs. Carla Humphrey', 'William Burch MD', 'Yvonne Robinson PhD', 'Martha Mcdonald DVM', 'Dr. Mary Schwartz', 'Taylor Green DDS', 'Christopher Simmons PhD', 'Rhonda Peterson MD', 'Jacqueline West DDS', 'Anne Lee DDS', 'Jacqueline Snow MD', 'Dr. Jennifer Shea', 'Clayton Williams DVM', 'Mr. Jeremiah Morris IV', 'Mr. John Harris', 'Mr. David Morales Jr.', 'Barbara Johnson MD', 'Megan Gutierrez MD', 'Larry Chandler Jr.', 'Ronald Matthews PhD', 'James Clark II', 'Cameron Roman Jr.', 'Mr. Ian Smith', 'Melissa Hunt MD', 'Alexandria Cooper MD', 'Mr. Andre Jensen', 'Renee Garcia MD', 'Christopher Smith Jr.', 'Mrs. Lori Rogers MD', 'Tammy Dunlap DVM', 'Matthew Sawyer PhD', 'Mike Harris PhD', 'Mrs. Christina Mitchell DDS', 'Evelyn Suarez DDS', 'Christina Alvarez PhD', 'Emily Duran MD', 'Todd Grant Jr.', 'Mrs. Veronica Sherman', 'Mr. Alan Anderson', 'Mr. Jason Jackson', 'Mrs. Jennifer Rivera', 'Dr. Terry Sanchez', 'Mr. Scott Sexton', 'Mrs. Wendy Hayes', 'Kenneth Santiago MD', 'Dr. Matthew Hernandez', 'Louis Hodges DDS', 'Dr. Douglas Duffy', 'Mrs. Michelle Patterson', 'Mrs. Jennifer Craig', 'Mr. Michael Graham', 'Dr. David Wright', 'Jeanne Fischer MD', 'Mrs. Amanda Rose', 'Rebecca Salazar DDS', 'Mrs. Kathleen Cook', 'Robert Olson DVM', 'Richard Cherry DDS', 'Jeffrey Shepard DVM', 'James Holland MD', 'Dr. Patricia Baker', 'Joshua Montgomery MD', 'Kevin Andrews PhD', 'Dr. Rachel Gilbert', 'Kenneth Avila Jr.', 'Miss Taylor Barron', 'Mr. Jason Lopez Jr.', 'Parker Carter MD', 'Dennis Wells DDS', 'Mrs. Carol White', 'Courtney Stephenson MD', 'Dr. Andrea Rose', 'Dr. Seth Villarreal DVM', 'Mrs. Sabrina Murillo MD', 'Mr. Eric Gordon', 'Mrs. Brenda Johnson DVM', 'Anthony Garrett DDS', 'Billy Franco PhD', 'Mr. Jeremiah Rogers', 'Mr. Donald Vang', 'Dr. Alexander Chang PhD', 'Mr. Robert Hendricks', 'Dr. Bryan Kim', 'Mrs. Cynthia Lopez', 'Dr. Laura Thompson', 'Ms. Stephanie Schwartz DDS', 'Mr. Anthony Deleon', 'Miss Sarah West', 'Dr. Devin Sharp PhD', 'Brittney Hammond DVM', 'Miss Chelsea Sullivan PhD', 'Dr. Jessica Love DVM', 'Leah Page DDS', 'Hannah Rose MD', 'Miss Norma Mcfarland', 'Dwayne Mathis Jr.', 'Cheryl Gay PhD', 'Patrick Morgan MD', 'Jeremy Rivera MD', 'Mr. Colton Collins II', 'Mr. Alexander Dalton', 'Dr. Nicholas Braun', 'Chris Palmer III', 'Mr. Mason Hernandez MD', 'Dr. Roberta Edwards', 'Dr. Kaitlin Barton', 'Dr. Nicholas Garcia', 'Mr. Trevor Woods', 'Dr. Bradley Jones DDS', 'Dr. Jennifer Thomas DDS', 'Dr. Adam Rivera', 'Mr. Sean Coleman PhD', 'Dr. Sheila Walton MD', 'Ian Sanchez DVM', 'Dr. Robert Mckinney', 'Laura Franco MD', 'Kelly Williams DDS', 'Mason Adams MD', 'Mr. Jason Davis', 'Dr. Daniel Flores', 'Mr. Ga

In [21]:
# Add the prefixes less than or equal to 4 to a new list.
prefixes = []
for name in students_to_fix:
    if len(name.split()[0]) <= 4:
        prefixes.append(name.split()[0])

##print(prefixes)

set(prefixes)

{'Adam',
 'Amy',
 'Anna',
 'Anne',
 'Carl',
 'Chad',
 'Cody',
 'Cory',
 'Dale',
 'Dana',
 'Dawn',
 'Dr.',
 'Emma',
 'Eric',
 'Erik',
 'Erin',
 'Gail',
 'Gary',
 'Gina',
 'Greg',
 'Ian',
 'Jill',
 'Jodi',
 'Joe',
 'John',
 'Jon',
 'Jose',
 'Judy',
 'Kara',
 'Kari',
 'Kim',
 'Kyle',
 'Leah',
 'Lisa',
 'Lori',
 'Luke',
 'Lynn',
 'Marc',
 'Mark',
 'Mary',
 'Mike',
 'Miss',
 'Mr.',
 'Mrs.',
 'Ms.',
 'Noah',
 'Omar',
 'Paul',
 'Ruth',
 'Ryan',
 'Sara',
 'Sean',
 'Seth',
 'Tara',
 'Tina',
 'Todd',
 'Toni',
 'Tony',
 'Troy'}

In [22]:
# Add the prefixes less than or equal to 4 to a new list.
suffix = []
for name in students_to_fix:
    if len(name.split()[-1]) <= 3:
        suffix.append(name.split()[-1])

print(suffix)

['MD', 'MD', 'MD', 'III', 'DVM', 'MD', 'MD', 'MD', 'DDS', 'DVM', 'II', 'MD', 'MD', 'DDS', 'MD', 'DDS', 'MD', 'MD', 'PhD', 'MD', 'DVM', 'Lee', 'MD', 'DDS', 'MD', 'MD', 'MD', 'MD', 'MD', 'MD', 'DDS', 'Jr.', 'DVM', 'MD', 'MD', 'PhD', 'IV', 'MD', 'DDS', 'DDS', 'DDS', 'MD', 'DDS', 'MD', 'DVM', 'IV', 'MD', 'DDS', 'MD', 'MD', 'DVM', 'Jr.', 'MD', 'PhD', 'II', 'MD', 'DDS', 'DDS', 'DDS', 'Jr.', 'III', 'MD', 'MD', 'MD', 'DDS', 'Jr.', 'DDS', 'DVM', 'DDS', 'DVM', 'MD', 'DDS', 'PhD', 'DDS', 'DDS', 'Jr.', 'Jr.', 'DVM', 'DDS', 'MD', 'MD', 'DVM', 'DDS', 'DVM', 'Jr.', 'MD', 'Jr.', 'MD', 'PhD', 'PhD', 'DDS', 'MD', 'DDS', 'DVM', 'Cox', 'DVM', 'MD', 'Jr.', 'MD', 'DDS', 'MD', 'MD', 'DDS', 'DDS', 'Roy', 'DDS', 'DDS', 'DDS', 'II', 'PhD', 'MD', 'PhD', 'DDS', 'MD', 'DDS', 'Jr.', 'Day', 'DDS', 'MD', 'PhD', 'DDS', 'Jr.', 'DDS', 'MD', 'MD', 'MD', 'MD', 'DDS', 'MD', 'DDS', 'PhD', 'DVM', 'DDS', 'MD', 'MD', 'MD', 'DDS', 'Jr.', 'Jr.', 'DDS', 'Jr.', 'MD', 'MD', 'PhD', 'PhD', 'DDS', 'MD', 'MD', 'III', 'DVM', 'PhD', 'Jr.', 'II', 'DDS', 'DDS', 'DVM', 'MD', 'II', 'MD', 'DDS', 'MD', 'DDS', 'PhD', 'DDS', 'DDS', 'II', 'DVM', 'DDS', 'Jr.', 'DVM', 'MD', 'MD', 'DVM', 'MD', 'DDS', 'DVM', 'DDS', 'MD', 'II', 'PhD', 'MD', 'MD', 'MD', 'DDS', 'MD', 'MD', 'DDS', 'DDS', 'MD', 'DDS', 'PhD', 'DVM', 'DVM', 'MD', 'MD', 'DDS', 'DDS', 'PhD', 'MD', 'IV', 'DDS', 'Jr.', 'DDS', 'Jr.', 'MD', 'MD', 'MD', 'DDS', 'MD', 'DVM', 'DVM', 'DDS', 'DDS', 'Jr.', 'MD', 'MD', 'DDS', 'DDS', 'MD', 'MD', 'MD', 'MD', 'DVM', 'MD', 'DVM', 'DVM', 'MD', 'DDS', 'MD', 'Jr.', 'DDS', 'MD', 'MD', 'DVM', 'Jr.', 'DDS', 'MD', 'MD', 'PhD', 'DDS', 'Jr.', 'MD', 'DDS', 'MD', 'DDS', 'Jr.', 'Jr.', 'DVM', 'MD', 'DDS', 'PhD', 'MD', 'PhD', 'MD', 'V', 'II', 'MD', 'PhD', 'DVM', 'MD', 'MD', 'PhD', 'MD', 'MD', 'MD', 'DDS', 'DVM', 'Jr.', 'MD', 'Jr.', 'Jr.', 'DDS', 'PhD', 'DVM', 'DVM', 'MD', 'MD', 'MD', 'DVM', 'MD', 'DDS', 'MD', 'DDS', 'Jr.', 'MD', 'DDS', 'DDS', 'Jr.', 'DVM', 'DVM', 'DDS', 'MD', 'MD', 'DVM', 'MD', 'MD', 'MD', 'DDS', 'MD', 'Jr.', 'MD', 'MD', 'PhD', 'PhD', 'DDS', 'DDS', 'DDS', 'MD', 'MD', 'PhD', 'Jr.', 'MD', 'DDS', 'III', 'DVM', 'Jr.', 'DDS', 'DDS', 'MD', 'DVM', 'MD', 'DDS', 'MD', 'PhD', 'DDS', 'Lee', 'MD', 'Jr.', 'MD', 'DVM', 'DDS', 'DDS', 'MD', 'MD', 'DVM', 'DVM', 'DVM', 'MD', 'DDS', 'DVM', 'DDS', 'MD', 'MD', 'MD', 'DDS', 'PhD', 'DDS', 'DVM', 'DDS', 'DVM', 'DDS', 'DVM', 'DVM', 'DDS', 'II', 'MD', 'III', 'DDS', 'DDS', 'DVM', 'DVM', 'MD', 'Jr.', 'II', 'MD', 'PhD', 'PhD', 'MD', 'DDS', 'DVM', 'DVM', 'MD', 'MD', 'DVM', 'DVM', 'PhD', 'Jr.', 'Jr.', 'MD', 'MD', 'DDS', 'DDS', 'III', 'PhD', 'Jr.', 'MD', 'MD', 'MD', 'DDS', 'MD', 'DDS', 'MD', 'DVM', 'PhD', 'MD', 'MD', 'PhD', 'Jr.', 'MD', 'MD', 'MD', 'MD', 'MD', 'MD', 'DVM', 'DVM', 'PhD', 'DDS', 'DDS', 'MD', 'DDS', 'MD', 'DVM', 'DVM', 'DDS', 'DVM', 'DDS', 'MD', 'MD', 'DVM', 'DVM', 'DDS', 'Jr.', 'PhD', 'MD', 'DVM', 'DVM', 'DDS', 'DVM', 'MD', 'MD', 'MD', 'II', 'DDS', 'DDS', 'DDS', 'MD', 'Jr.', 'MD', 'Jr.', 'DDS', 'MD', 'MD', 'DVM', 'MD', 'DDS', 'DDS', 'PhD', 'Jr.', 'Jr.', 'Jr.', 'DDS', 'Jr.', 'MD', 'MD', 'DDS', 'MD', 'Jr.', 'MD', 'DDS', 'Jr.', 'DDS', 'MD', 'MD', 'Jr.', 'PhD', 'DDS', 'MD', 'II', 'PhD', 'DVM', 'MD', 'DDS', 'PhD', 'MD', 'MD', 'DDS', 'Jr.', 'MD', 'DVM', 'MD', 'MD', 'MD', 'MD', 'MD', 'DDS', 'DVM', 'PhD', 'DVM', 'III', 'Jr.', 'DVM', 'MD', 'MD', 'V', 'Jr.', 'MD', 'DVM', 'MD', 'DDS', 'DVM', 'DDS', 'Jr.', 'MD', 'PhD', 'DVM', 'DDS', 'PhD', 'MD', 'DDS', 'DDS', 'MD', 'DVM', 'IV', 'Jr.', 'MD', 'MD', 'Jr.', 'PhD', 'II', 'Jr.', 'MD', 'MD', 'MD', 'Jr.', 'MD', 'DVM', 'PhD', 'PhD', 'DDS', 'DDS', 'PhD', 'MD', 'Jr.', 'MD', 'DDS', 'MD', 'DDS', 'DVM', 'DDS', 'DVM', 'MD', 'MD', 'PhD', 'Jr.', 'Jr.', 'MD', 'DDS', 'MD', 'DVM', 'MD', 'DVM', 'DDS', 'PhD', 'PhD', 'Kim', 'DDS', 'PhD', 'DVM', 'PhD', 'DVM', 'DDS', 'MD', 'Jr.', 'PhD', 'MD', 'MD', 'II', 'III', 'MD', 'DDS', 'DDS', 'PhD', 'MD', 'DVM', 'MD', 'DDS', 'MD', 'DDS', 'Jr.', 'DDS', 'DDS', 'MD', 'IV', 'Jr.', 'DDS', 'DDS', 'Jr.', 'DVM', 'DVM', 'DVM', 'DVM', 'MD', 'DVM', 'DDS', 'MD', 'MD', 'DDS', 'DDS', 'DVM', 'III', 'DVM', 'MD', 'DVM', 'DDS', 'MD', 'MD', 'DVM', 'DVM', 'MD', 'III', 'DDS', 'MD', 'DDS', 'DVM', 'Jr.', 'III', 'MD', 'MD', 'PhD', 'DVM', 'DDS', 'MD', 'Jr.', 'DDS', 'MD', 'II', 'MD', 'Jr.', 'DDS', 'PhD', 'DDS', 'DDS', 'II', 'Jr.', 'DDS', 'MD', 'II', 'MD', 'MD', 'MD', 'Jr.', 'DDS', 'MD', 'DVM', 'PhD', 'MD', 'DVM', 'DDS', 'DDS', 'DVM', 'DDS', 'DDS', 'MD', 'MD', 'MD', 'MD', 'DDS', 'DVM', 'PhD', 'DDS', 'DDS', 'MD', 'MD', 'MD', 'DDS', 'DVM', 'MD', 'II', 'MD', 'Jr.', 'Jr.', 'MD', 'MD', 'MD', 'MD', 'DVM', 'MD', 'Jr.', 'PhD', 'PhD', 'PhD', 'DDS', 'Jr.', 'DVM', 'DDS', 'MD', 'DVM', 'PhD', 'MD', 'Jr.', 'Jr.', 'DVM', 'MD', 'DDS', 'MD', 'MD', 'Lee', 'MD', 'MD', 'MD', 'DDS', 'PhD', 'MD', 'PhD', 'MD', 'DVM', 'MD', 'MD', 'MD', 'DDS', 'II', 'DVM', 'Jr.', 'DVM', 'MD', 'Jr.', 'DDS', 'DVM', 'DDS', 'Jr.', 'DVM', 'Jr.', 'DDS', 'MD', 'PhD', 'DDS', 'DDS', 'DVM', 'MD', 'MD', 'PhD', 'DDS', 'DDS', 'DDS', 'DDS', 'MD', 'DVM', 'DVM', 'DVM', 'DDS', 'MD', 'MD', 'MD', 'Jr.', 'PhD', 'MD', 'Jr.', 'DVM', 'DDS', 'DVM', 'MD', 'DVM', 'MD', 'DDS', 'DDS', 'PhD', 'DDS', 'Jr.', 'DDS', 'MD', 'MD', 'MD', 'MD', 'DDS', 'DVM', 'MD', 'MD', 'PhD', 'MD', 'MD', 'II', 'MD', 'Jr.', 'PhD', 'MD', 'PhD', 'MD', 'MD', 'DDS', 'Jr.', 'PhD', 'DDS', 'MD', 'DDS', 'DDS', 'MD', 'MD', 'MD', 'Jr.', 'DDS', 'DDS', 'MD', 'MD', 'MD', 'MD', 'IV', 'Jr.', 'MD', 'DDS', 'MD', 'DDS', 'MD', 'MD', 'Jr.', 'MD', 'DVM', 'DVM', 'DVM', 'MD', 'MD', 'DVM', 'DVM', 'PhD', 'Jr.', 'PhD', 'DVM', 'Jr.', 'MD', 'MD', 'DDS', 'III', 'DVM', 'DDS', 'Jr.', 'MD', 'MD', 'Jr.', 'MD', 'MD', 'DVM', 'Jr.', 'Jr.', 'DDS', 'PhD', 'DDS', 'DDS', 'DDS', 'Jr.', 'Jr.', 'MD', 'DVM', 'DDS', 'MD', 'MD', 'PhD', 'DDS', 'MD', 'DDS', 'DVM', 'DVM', 'MD', 'DDS', 'MD', 'MD', 'MD', 'Jr.', 'MD', 'DVM', 'DDS', 'MD', 'PhD', 'MD', 'II', 'Jr.', 'III', 'MD', 'PhD', 'MD', 'MD', 'PhD', 'II', 'DDS', 'DVM', 'DDS', 'MD', 'DDS', 'MD', 'DVM', 'MD', 'III', 'DDS', 'MD', 'DVM', 'MD', 'II', 'DDS', 'MD', 'MD', 'DDS', 'MD', 'MD', 'DVM', 'MD', 'MD', 'MD', 'II', 'DDS', 'Jr.', 'MD', 'DDS', 'MD', 'MD', 'MD', 'MD', 'DDS', 'IV', 'MD', 'Jr.', 'III', 'DDS', 'DDS', 'MD', 'DDS', 'DVM', 'DVM', 'PhD', 'MD', 'II', 'Li', 'DVM', 'MD', 'DVM', 'DDS', 'DDS', 'DDS', 'DVM', 'MD', 'DVM', 'MD', 'MD', 'MD', 'MD', 'Jr.', 'DVM', 'MD', 'MD', 'MD', 'MD', 'DDS', 'MD', 'PhD', 'DDS', 'MD', 'MD', 'DDS', 'Jr.', 'DDS', 'DDS', 'DVM', 'DDS', 'DDS', 'MD', 'Jr.', 'DDS', 'PhD', 'Jr.', 'DDS']

In [23]:
set(suffix)

{'Cox',
 'DDS',
 'DVM',
 'Day',
 'II',
 'III',
 'IV',
 'Jr.',
 'Kim',
 'Lee',
 'Li',
 'MD',
 'PhD',
 'Roy',
 'V'}

In [24]:
# Strip "Mrs." from the student names
for name in students_to_fix:
    print(name.replace("Dr. ", ""))

Richard Scott
Jordan Carson
Madeline Snyder MD
Mr. Dylan Taylor MD
Scott Gill
Miss Madison Everett
Virginia Ramirez MD
Joseph Morales III
Angela Perkins DVM
Heather Allen MD
Luke Lowery MD
Larry Hines
Emily Cardenas MD
Mrs. Elizabeth Espinoza DDS
Mrs. Lisa Becker
Mr. Travis Young
Paula Fernandez DVM
Xavier Bell II
Andrew Hanson MD
Mr. Roberto Wright MD
Mr. Dale Miller
Mary Gonzalez DDS
Mrs. Cindy Brown
James White MD
Donald Gill DDS
Mrs. Catherine Williams MD
Ashley Caldwell MD
Mr. Jared Campbell
Michael Moreno PhD
Tara Parker MD
Shawn Williams DVM
Alicia Martinez
Mr. Timothy Anderson
Mrs. Paula Lee
Mr. Elijah Hall
Mr. Raymond Stone
John Dickerson MD
Mr. Alex Franklin
Mrs. Jessica Dunn
Mr. Michael Stevenson
Jason Jones DDS
Adriana Wade MD
Erica Hurley MD
Garrett Wright
Mr. James Allen
Mr. Timothy Harper MD
Dale Brown MD
Christina Moore
Angela Peterson MD
Jennifer Ferguson MD
Anthony Wilson DDS
Jessica Lopez
David Miller Jr.
John Jones
Ms. Samantha Brown
Cynthia Hansen DVM
Rebecca Montoya MD
Jacob Matthews
Jacob Bell
Mr. Bruce Thomas
Robert Martin MD
Mrs. Marcia Jones PhD
Reginald Garcia IV
Patricia Smith MD
Amy Dyer DDS
Brian Hall DDS
Douglas Levy DDS
Mr. Eric Ibarra
Benjamin Ramirez MD
Raymond Freeman DDS
Carla Reeves MD
Donald Williams
Mr. John Carter
William Jackson DVM
Mr. Mitchell Cooper
Kevin Brown IV
Mrs. Kathleen Reed
Donna Robinson MD
Mrs. Dawn Olson DDS
Mr. Dustin Glover
Alexis French MD
Lisa Guerrero MD
David Nguyen DVM
William Washington Jr.
Julie Patterson MD
Mr. James Kelly
Robert Martin
Darlene Thomas PhD
Mr. Juan Jenkins
Mr. Juan Bryant II
Mr. Matthew Coleman
Bonnie Hammond MD
Kathleen Harris DDS
Steven Velez DDS
Tammy Cruz DDS
Marie Williams
Kenneth Paul Jr.
Mr. Jose Morris
Scott Rivers III
Melissa Rodriguez MD
Geoffrey Ortiz MD
Matthew Stewart MD
Sandra Thompson DDS
Mark Myers Jr.
Mrs. Maria Smith DDS
Kimberly Clements
Kenneth Webb
Amanda Patterson DVM
Miss Tara Banks DDS
Nancy Brown DVM
Chase Boyd MD
Mr. James Spence
Miss Colleen Stewart DDS
Mr. Todd Greene PhD
Amanda Hamilton DDS
Mrs. Lisa Rowland
Mr. Eric Moon
Mrs. Alicia Kelly DDS
Mr. Michael Norton Jr.
Mr. James Crosby
Mr. Sean Pena Jr.
Kathy Lucero DVM
Dustin Ferguson DDS
James Patterson
Juan Cobb MD
Victoria Garcia MD
Michael Evans DVM
Miss Ebony Bell
Mr. Justin Mullins DDS
Mrs. Jill Walker
Mr. Eric Hicks
Tara Williams DVM
Jessica Watkins
Mr. Joseph Turner
Cody Mueller Jr.
Kiara Williams MD
Mathew White Jr.
Steve Hendricks MD
Mr. Victor Duarte
Stacy Maynard
Mr. Steven Snyder PhD
Jessica Warner PhD
Trevor Summers DDS
Maria Doyle MD
Stacie Walker DDS
Megan House DVM
Ms. Deborah Coleman
Ryan Barker
Mr. Michael Cox
Mrs. Rebecca Martin DVM
Sara Jacobs MD
Mr. Jason Daugherty Jr.
Mrs. Natalie Holder MD
Charles Hernandez DDS
Charles Lawrence
Mr. Tyler Walker
Janet Whitaker MD
Jeremy Watkins MD
David Martinez DDS
Kimberly Olsen DDS
Nicole Roy
Mr. Justin Maxwell
Danielle Robinson DDS
Mrs. Susan Chase DDS
Mr. Alex Gonzales DDS
Leonard Webster II
David Taylor PhD
Mr. Christopher Stuart
Mr. Kevin Wilson
Mr. John Walters
Breanna Peterson MD
Terri Quinn PhD
Christian Reynolds DDS
Mr. Donald Gray
Shawn Brown
Samantha Salas MD
Valerie Thomas DDS
Mrs. Gina Anderson
Michael Stein Jr.
Mr. Robert Day
Justin Hernandez DDS
Mrs. Mikayla White
Edward Palmer
Elizabeth Coleman MD
Alexandra Hood PhD
Michael Gonzalez DDS
Ryan Phillips Jr.
Ashley Jones DDS
Susan Trujillo MD
Carol Baker MD
Kelly Ibarra MD
Mrs. Crystal Perez
Mr. Joshua Jensen MD
Ms. Vanessa Ortiz DDS
Mr. Jay Navarro
Jimmy Smith MD
John Compton DDS
Mario Wheeler PhD
Mr. Joshua Simon
Alicia Ferguson DVM
Amy Melendez
Gloria Fritz DDS
Michael Miller
Mrs. Alexandra Taylor
Jennifer Ramirez MD
Mrs. Amy Walker MD
David Dickson MD
Amanda Mills DDS
Mr. Jason West
Mr. Joshua Hall
Mrs. Elizabeth Mitchell
Sarah Miller
Allen Snyder Jr.
Calvin Williams Jr.
Tammy Shelton
Miss Jennifer Gibson
Miss Christy Robinson
Mr. Michael Rhodes
Deborah Huffman DDS
Ronald Torres Jr.
Mr. Oscar Bautista
Ellen Mcgee MD
Emily Andrews MD
Richard Williams PhD
Mr. Michael Baker PhD
Robert Taylor
Traci Obrien DDS
Robert Harris MD
Diana Martin
Logan Ward MD
Mrs. Janice Dixon
Gabriel Smith III
Linda Duran DVM
Ronald Mayer PhD
Mr. David Smith
Brian Pitts Jr.
Ms. Stephanie Rose
Mr. Richard Stephens
Miss Kimberly Joseph
Bruce Thompson II
Tony Adams DDS
Annette Collins DDS
Mr. Chad Hendricks
Lindsey Tyler DVM
Michael Drake MD
Jeremy Sanders II
Mr. George Goodwin MD
Amanda Ramirez DDS
Aaron Morris MD
Mrs. Michelle Butler
Mr. Robert Carson
Mrs. Jennifer Martin DDS
Miss Amber Wallace
Mrs. Mary Hardy
Jennifer Smith PhD
Jodi White DDS
Mr. Ryan Strickland
Mr. Michael Koch
Mrs. Kara Rodriguez DDS
Mr. Ryan Adams
Austin Johnson II
Mr. Samuel Robertson DVM
Benjamin Vargas DDS
Mrs. Wendy Thomas
Bryan Conway Jr.
Brittany Hatfield DVM
Mrs. Casey Hayes
Johnny Byrd MD
Nicole Burke MD
Brett Banks DVM
Mrs. Lori Johnson
Michael Shea MD
Jesse Thompson DDS
Brooke Simpson DVM
Mr. Michael Davis
Mr. Thomas White
Jessica Scott DDS
Mr. Michael Burton
Mrs. Laurie Brown
Cindy Logan
Nicholas Jones MD
Ronald Moore II
Mr. Jonathon Patrick
Mr. Andrew Kemp
Alexander Garcia PhD
Brett Campbell MD
Mrs. Paige Hall
Danielle Smith MD
Catherine Mendez MD
Mr. David Mcdonald
Mrs. Ashley Porter DDS
Jason Mcdowell MD
Mr. Martin Lozano
Bruce Hendrix MD
Pamela Cox DDS
Kristina Turner
Samantha Buchanan DDS
Mr. Cameron Singh
Mr. Steven Davis
Ruth Martinez MD
George White DDS
Michael Johnson
Joshua Garrison PhD
Mr. Nicholas Rodriguez DVM
Ms. Sarah Ray DVM
Natalie Rivera MD
Tracy Powell
Mr. Jason Chavez MD
Mrs. Leslie Mathews
Patrick Newman DDS
Mr. Michael Chapman DDS
Jennifer Long PhD
Matthew Anthony MD
Robert Garrison IV
Jamie Anderson DDS
William Gonzalez Jr.
Jennifer Weiss
Cynthia Torres
John Miranda DDS
Brian Matthews Jr.
Mr. Christopher Quinn
Mrs. Jacqueline Rose
Mrs. Angela Gray
Mrs. Tara Carpenter
Shannon Stevenson MD
Kaitlin Warner MD
Jessica Fowler MD
Mrs. Catherine Armstrong
John Mullins DDS
Christina Benson MD
Amy Martinez DVM
Ashley Edwards DVM
Melissa Herrera DDS
Adam Arroyo DDS
Amanda Cochran
Eric Richards Jr.
Mrs. Angela Martinez
Natalie Garcia MD
Mr. Dennis Duke
Christopher Fleming MD
Misty Beck DDS
Sharon Lloyd DDS
Mrs. Laura Malone MD
Gabriel Flores MD
Russell Gallegos
Kyle Walker MD
Caleb Oliver MD
Mr. Cameron Erickson
Pamela Oliver DVM
Mariah Russell MD
Jonathan Fisher DVM
Ms. Sarah Mcintosh DVM
Lynn Jones MD
Allison Martinez DDS
Jeffrey Zamora MD
Kenneth Munoz Jr.
Ellen Mcclure DDS
Samantha Ballard MD
Mariah Franco MD
Mr. Daniel Smith DVM
Jon Delgado Jr.
Mrs. Anna Dickerson
Mrs. Cynthia Martinez DDS
Angela Hamilton MD
Mrs. Stephanie Stone
Marcus Kim MD
Jordan Brewer PhD
Mrs. Veronica Neal
Mike Alvarez
Patricia Lee DDS
Andrew English Jr.
Jennifer Martinez MD
Donna Humphrey
Mrs. Jennifer Tucker DDS
Mrs. Jamie Bond
Judy Mills MD
Christina Jackson DDS
Mr. Raymond Cox Jr.
Donna Cooper
Jeffrey Mcclain Jr.
Mr. Joseph Hill
Bryan Shaffer DVM
Julie Bond MD
Michael Hunter DDS
Melissa Rodriguez PhD
Deborah Rodriguez MD
Mrs. Andrea Wilson
Jonathan Woods PhD
Jacob Ballard MD
Mr. Brian Poole V
Jeffrey Kim II
Mr. Michael Gonzalez
Kevin Brooks MD
April Hansen PhD
Mr. Brian Austin
Sara Cooper DVM
Kelsey Ellis MD
Deborah Madden MD
Brooke Silva
Melissa Allen PhD
Karen Thomas MD
Mrs. Sophia Harper
Tara Singleton MD
Alison Flores
Kenneth Adams MD
Mrs. Natasha White
Amanda Sanchez DDS
Scott Campbell DVM
Matthew Alexander Jr.
Shane Gilmore MD
Miss Paula Lawson
Mrs. Theresa Roberts
Kevin Reynolds Jr.
Mr. David Anderson
Gabrielle Morris
Jacob Skinner Jr.
Miss Lisa Kennedy
Timothy Byrd DDS
Haley Jordan PhD
Deborah Mack DVM
Mckenzie Morris DVM
Megan Saunders MD
Tina Meyer MD
Harold Sutton MD
James Allen DVM
Lauren Perry
Eric Riley MD
Jamie Rogers DDS
Natasha Lee MD
Ms. Paula Taylor
Theodore Mendez DDS
Ms. Rebecca Johnson
Mr. Dennis Gibson Jr.
Mrs. Sherry Flores MD
Alejandro Swanson
Tiffany Peters DDS
Christopher Crawford DDS
Jimmy Shea Jr.
Mr. Joshua Cunningham
Mr. Travis Jackson
Mary Johnson
Mr. Patrick Duarte
Mr. Adam Hernandez
Susan Wright
Miss Stephanie Perry DVM
Tracey Gonzalez
Paul Hernandez DVM
Mrs. Jasmine Schroeder
Mr. Adam Sosa
Linda Sanchez DDS
Mrs. Danielle Jones
Benjamin Henry MD
Mr. Randy Reyes
Mr. Russell Elliott
Mr. Thomas Smith MD
Rachel Hanna DVM
Robert Stephens MD
Sean Duncan MD
Maria Adams MD
Mrs. Theresa Bauer
Teresa Blair DDS
Jennifer Campbell MD
Melody Garcia
James Reed Jr.
Elizabeth Wallace MD
Mrs. Gina Williams
Emily Price MD
Mrs. Bonnie Boyd PhD
Harry Campbell
Kevin Simon
Eric Lambert PhD
Mr. John Mathis
Jason Bush DDS
Ms. Amy House
Kevin Diaz
Mr. Kevin Benjamin
Mrs. Michelle Dickerson DDS
Alexandra Mays
Mrs. Jessica Hebert
George Cline
Mrs. Whitney Scott
Jennifer Jenkins DDS
Mr. Gregg Rosario
Scott Roth MD
Evelyn Kirby MD
Miranda Thompson PhD
Carla Ross
Mrs. Tanya Odom
Jeffery Baker Jr.
Mrs. Melissa Medina
Daniel Lara MD
Mrs. Nicole Vazquez
Emily Gutierrez DDS
Stephanie Smith
Derrick Hughes III
Mr. Eduardo James
Mr. Michael Cook
Mr. David Hill
Ryan Orozco DVM
Joshua Rivera Jr.
Marc Harmon DDS
Mr. Keith Peters DDS
Amanda Freeman MD
Michelle Carlson
Stephen Vargas
Colleen Frederick DVM
Harry Chang
Taylor Grant MD
Mrs. Renee Thomas DDS
Shannon Johnson MD
Mrs. Christina Horne
Mrs. Deborah Walters PhD
Mr. Jesse Gonzalez
Larry Martinez DDS
Mrs. Anita Lee
James Jones
Tammy Jones
Michael Golden MD
Gavin Tate
Christopher Collins
Timothy Guzman Jr.
Mr. Alexander Thomas
James Lewis
Mr. Andrew Miller
Mrs. Kelly Hall
Kayla Lowe
Joseph Park
Alfred Foster
Amy Stephenson MD
Stephen Black DVM
Daryl Smith
Stuart Gross DDS
Michael Hardy DDS
Mr. Kenneth Chase
Mrs. Anna Everett MD
Mr. Joshua Young
Mrs. Robin Lopez MD
Elizabeth Benson
Casey Hogan
Elizabeth Peterson DVM
Marilyn Vasquez DVM
Mr. Jack Reed
Zachary Shields DVM

Mrs. Molly Lopez MD
Stephanie Jones
Benjamin George DDS
David Thomas DVM
Jill Hudson DDS
Mary Mccormick MD
Michelle Smith MD
Carl Burns MD
Mr. Juan Buckley DDS
Michelle Brown
Jose Huffman PhD
Deanna Mccarthy DDS
Mrs. Robin Hughes
Laura Shannon DVM
Mary Fox DDS
Ms. Jamie Sanchez
Meredith Tucker DVM
Jose Manning DDS
Lisa Bruce DVM
Crystal Howard DVM
Mrs. Tracy Williams
Mr. Jeffery Diaz
Julie Baker DDS
Miss Danielle Adams
Lonnie Allen II
Mr. Bryan Brooks
Ashley Jimenez MD
Tyrone Clark III
Eric Mullins DDS
Mr. Jonathan Walker
Patricia Villarreal DDS
Mrs. Megan Kaufman DVM
Mathew Thompson DVM
Mrs. Whitney Figueroa
Miss Debbie Chavez
Emma Bates MD
Jeffrey Nelson Jr.
Michael Mann II
Mrs. Karina Perry
Chelsey Williams MD
Jessica Sanchez PhD
Joseph Ellis PhD
Mrs. Heather Gregory
Mr. Steven Davies
Lauren Brown
Brett Garcia MD
Anthony Davis DDS
Anita Salazar DVM
Joseph Jones DVM
Edward Davis MD
Mr. Brian Abbott
Nicole Pennington MD
Kelly Doyle DVM
Franklin Chen DVM
Mr. Brandon Young
Nathan Welch PhD
Katrina Farmer
David Johnson Jr.
Timothy Chavez Jr.
Michele Oconnell MD
Elizabeth Tran MD
Grace Martin
Sarah Chaney DDS
Mrs. Brooke Henry DDS
Lisa Coleman
Brian Powell III
Logan Oconnell PhD
Lance Rangel Jr.
Nicole King
Mr. John Carroll
Mr. Anthony Mccormick
Samuel Ruiz MD
Ms. Jennifer Richard
Mr. Stephen Cochran
Gary Jarvis MD
Dustin Stephenson MD
Mr. Derrick Campbell DDS
Lori Brown MD
Mrs. Brooke Rodgers
Mr. David Moss
Mr. Joseph Knight DDS
Mrs. Brittany Duncan MD
Mrs. Jennifer Edwards DVM
William Cook PhD
Kristina White MD
Tonya Henry MD
Robert Sanders PhD
Noah Herrera Jr.
Linda Marshall MD
James Davis MD
Dawn Gilbert MD
Dennis Andrews
Mr. John Evans
Mr. Michael Brooks
Shannon Ortiz MD
Mrs. Brenda Bishop MD
Wanda Miller MD
Mrs. Sheila Wagner
Mrs. Kathleen Johnson DVM
Shannon Russo
Chad Chavez DVM
Mr. William Holt
Paul Jensen PhD
Cassandra Gardner DDS
Mrs. Susan Klein
Amanda Nguyen
Mrs. Leslie Esparza
Mrs. Jacqueline Simpson
Mrs. Tammy Crane
Wendy Oliver
Katelyn Mejia DDS
Miguel Rivera
Mrs. Nancy Landry
Renee Stewart MD
Breanna Mcintyre DDS
Sarah Fischer MD
Ronald Berry DVM
Mrs. Amanda Cook
Monica Gonzalez
Miss Jennifer Moore
Crystal Watson DVM
Suzanne Edwards DDS
Lance Brown DVM
Olivia Taylor DDS
Mrs. Lauren Lewis
Jillian Proctor MD
Yvette Jacobson MD
Chelsea Rhodes DVM
Robert Brown DVM
Maria Brooks DDS
Eric Johnson Jr.
Kelly Webb PhD
Valerie Chen
Mrs. Taylor Martin
Andre Casey
Mr. Stephen Clements
Kevin Morrow MD
Louis Skinner
Adam Walker DVM
Mr. Steven Smith
Willie King
Miranda Stanley DVM
Travis Johnson
Mr. Christopher Cook
Mr. Martin Hensley DDS
Kelly Haynes DVM
Mr. Alexander Foster MD
Mr. William Rodgers
Anne Larsen MD
Sherry Johnson MD
Victor Chavez II
Brandon Dougherty DDS
Elizabeth Young DDS
Mr. Joshua Lucas
Michael Walsh DDS
Mrs. Lauren Campbell
Troy Camacho MD
Richard Ellis Jr.
Mr. Brandon Johnson
Mrs. Brooke Campbell
Karen Kelley
Mr. Jason Simmons
Mr. Larry Francis MD
Mr. Christopher Griffin
Mr. Dean York
Charles Goodman Jr.
Miss Erin Bradley DDS
Mr. Michael Allen
Kelly Romero MD
Anna Yang MD
John White DVM
Mr. James Barnes
Mr. Carlos Warner
April Calderon MD
Mrs. Kimberly Key DDS
Eric Park DDS
Patrick Barker PhD
Michael Singh Jr.
Jonathan Smith Jr.
Allen Morris Jr.
Mr. Lee Rose
Carl James
Kimberly Benjamin
Mr. Lucas Smith
Mr. Jason Grant DDS
Aaron Solis Jr.
Ryan Graham MD
Justin Morgan MD
Mrs. Victoria Cochran
Ryan Roberts
Katie Strickland DDS
Emma Perry MD
Mr. Daniel Mckinney Jr.
Mr. Paul Farmer
Stephanie Howard MD
Mandy Mcconnell DDS
Mrs. Angelica Hall
Christopher Petty Jr.
Megan Shaw DDS
Bianca Huynh MD
Miss Christina Burns
Melissa Dunn MD
Mr. Derek Wilson
Mr. Angel Johnson
Mrs. Nicole Duran
Michael Garcia Jr.
Mrs. Bethany Fisher PhD
Mr. Daniel Nguyen DDS
Wanda Moore MD
Charles Short II
Kimberly Jacobson PhD
Debbie Brown DVM
Mr. Michael Dyer MD
Joshua Kim DDS
Daniel Fitzpatrick PhD
Jordan Waller MD
Mr. Jesse Bell
Mario Myers MD
Terry Adams DDS
Derek Barker Jr.
Mrs. Renee Gordon
Mr. Vincent King
Oscar Lawson MD
Lisa Zimmerman DVM
Mr. Phillip Vaughan
Joseph Dyer MD
Austin Cole
Mrs. Amanda Martin
John Thomas MD
Sierra Dominguez MD
Mrs. Katie Weber MD
Ms. Nancy Green
Mrs. Pamela Garcia
Danielle Stanton MD
Elizabeth Logan DDS
Courtney Wall DVM
Karen Harris PhD
Mrs. Amanda Herring
David Miller
Mr. Eric Anderson
Mrs. Sheena Bailey DVM
Zachary Garrett III
Thomas Harrison Jr.
Megan Bennett DVM
Mr. Steven Harrison
Amy Mcintosh MD
Frank Anderson
Jamie Dawson MD
Mr. Andrew Mitchell V
Travis Richmond
Mrs. Amy Cain
Aaron Davis Jr.
Thomas Burgess MD
Amanda Hale DVM
Derek Cooke MD
Daniel Bowman
Jonathan Palmer
Lori Mitchell DDS
Mr. Richard Armstrong
Timothy Johnson
Mrs. Pam Lewis DVM
Amy Gutierrez DDS
Christina Flores
Brian Bailey Jr.
Mrs. Carla Humphrey
William Burch MD
Yvonne Robinson PhD
Martha Mcdonald DVM
Mary Schwartz
Taylor Green DDS
Christopher Simmons PhD
Rhonda Peterson MD
Jacqueline West DDS
Anne Lee DDS
Jacqueline Snow MD
Jennifer Shea
Clayton Williams DVM
Mr. Jeremiah Morris IV
Mr. John Harris
Mr. David Morales Jr.
Barbara Johnson MD
Megan Gutierrez MD
Larry Chandler Jr.
Ronald Matthews PhD
James Clark II
Cameron Roman Jr.
Mr. Ian Smith
Melissa Hunt MD
Alexandria Cooper MD
Mr. Andre Jensen
Renee Garcia MD
Christopher Smith Jr.
Mrs. Lori Rogers MD
Tammy Dunlap DVM
Matthew Sawyer PhD
Mike Harris PhD
Mrs. Christina Mitchell DDS
Evelyn Suarez DDS
Christina Alvarez PhD
Emily Duran MD
Todd Grant Jr.
Mrs. Veronica Sherman
Mr. Alan Anderson
Mr. Jason Jackson
Mrs. Jennifer Rivera
Terry Sanchez
Mr. Scott Sexton
Mrs. Wendy Hayes
Kenneth Santiago MD
Matthew Hernandez
Louis Hodges DDS
Douglas Duffy
Mrs. Michelle Patterson
Mrs. Jennifer Craig
Mr. Michael Graham
David Wright
Jeanne Fischer MD
Mrs. Amanda Rose
Rebecca Salazar DDS
Mrs. Kathleen Cook
Robert Olson DVM
Richard Cherry DDS
Jeffrey Shepard DVM
James Holland MD
Patricia Baker
Joshua Montgomery MD
Kevin Andrews PhD
Rachel Gilbert
Kenneth Avila Jr.
Miss Taylor Barron
Mr. Jason Lopez Jr.
Parker Carter MD
Dennis Wells DDS
Mrs. Carol White
Courtney Stephenson MD
Andrea Rose
Seth Villarreal DVM
Mrs. Sabrina Murillo MD
Mr. Eric Gordon
Mrs. Brenda Johnson DVM
Anthony Garrett DDS
Billy Franco PhD
Mr. Jeremiah Rogers
Mr. Donald Vang
Alexander Chang PhD
Mr. Robert Hendricks
Bryan Kim
Mrs. Cynthia Lopez
Laura Thompson
Ms. Stephanie Schwartz DDS
Mr. Anthony Deleon
Miss Sarah West
Devin Sharp PhD
Brittney Hammond DVM
Miss Chelsea Sullivan PhD
Jessica Love DVM
Leah Page DDS
Hannah Rose MD
Miss Norma Mcfarland
Dwayne Mathis Jr.
Cheryl Gay PhD
Patrick Morgan MD
Jeremy Rivera MD
Mr. Colton Collins II
Mr. Alexander Dalton
Nicholas Braun
Chris Palmer III
Mr. Mason Hernandez MD
Roberta Edwards
Kaitlin Barton
Nicholas Garcia
Mr. Trevor Woods
Bradley Jones DDS
Jennifer Thomas DDS
Adam Rivera
Mr. Sean Coleman PhD
Sheila Walton MD
Ian Sanchez DVM
Robert Mckinney
Laura Franco MD
Kelly Williams DDS
Mason Adams MD
Mr. Jason Davis
Daniel Flores
Mr. Gary Anderson DDS
Tyler Randall Jr.
Joshua Santiago DDS
Laurie Moore DDS
Susan Walsh
Kristin Smith MD
Mrs. Denise Vasquez
Miss Bridget Ryan
Joseph Morgan IV
Carlos Adkins Jr.
Michael Craig DDS
Brent Schwartz
Mrs. Melissa Vasquez
Ms. Sandra Ware
Becky Powell
Matthew Cooper DDS
Mark Livingston Jr.
Mr. Michael Martin DVM
Kari Anderson DVM
Mrs. Kaitlin Oconnor DVM
Crystal Miller DVM
Mrs. Margaret Watson
Mr. John Martin
Richard Price MD
Jennifer Powell DVM
Sheri Davis DDS
Traci Blanchard MD
Mrs. Nancy Blair
Aaron Carpenter MD
Monica Wilson
Kristin Holland
Kimberly Knight DDS
Mrs. Brittany Ford DDS
Benjamin Singh DVM
Amber Owens
Michael Williams III
Mrs. Wendy Gomez DVM
Kara Stuart MD
Kayla Torres DVM
Bobby Hart DDS
Mark Russell MD
John Duncan MD
Rachel Gonzalez DVM
Mrs. Katherine Jones
Brian Harrington DVM
Mrs. Theresa Winters
Mr. Chad Hale
Miguel Cook MD
Eric Evans III
John Murray DDS
Andrew Young
Mrs. Jordan White MD
Erica Stevenson
Mr. Stephen Hardy
Paul Stanley DDS
Christina Gonzalez DVM
Anthony Jimenez
Christopher Thornton Jr.
Mrs. Julie Powers
Christopher Sullivan
Joyce Pace
Alyssa Patrick
Adam Hayes III
Brittany Holmes MD
Mrs. Angela Floyd
Ms. Angela Hernandez
Michael Cummings MD
Brittany Sanchez PhD
Nicole Mclean DVM
Melissa Fernandez
Scott Bishop DDS
Mrs. Alexandra Hamilton
Jacob Taylor MD
Michael Moore Jr.
Ms. Alicia Zhang DDS
Mrs. Sharon Rose
Amber Ray MD
Mr. Jeremy Chang
Joseph Hudson II
Jessica Hughes MD
William Brooks Jr.
Mr. Jacob Frost
Mrs. Melissa Ingram DDS
Robert Murphy
Mrs. Melanie Martinez PhD
Mr. Stephen Berry
Judith Reese
Sarah Young DDS
Angela Thompson DDS
Mr. Darren Taylor
Daniel Welch II
Roger Horton Jr.
Virginia Evans
John Dyer
Jeffery Brown DDS
Paul Cox MD
Mrs. Angela Williams
Cory Marshall II
Mrs. Megan Clark MD
Jennifer Hogan MD
Natalie Davis MD
Sarah Johnson
Corey Mathis
Mr. Joshua Thompson Jr.
Nancy Stewart DDS
Mr. Brian Glover
Roberta Garcia MD
Erin Conrad DVM
Karla Love
Tina White PhD
Leslie Wright MD
Ms. Brittney Nunez
Mrs. Susan Mccormick
Amanda Wolf DVM
Mr. Mitchell Coleman
Miss Christy Harris
Dylan Foley DDS
Mr. Lance Stark
Ricky Murphy DDS
Mr. Elijah Anderson
Kristen Dennis DVM
Mr. Casey Vang
William Young DDS
Ms. Kristina Cook
Mrs. Kimberly Floyd DDS
Mr. Timothy Brooks
Mrs. Samantha Jackson
Miss Lori Doyle
Ms. Karen Villegas MD
Brenda Maldonado MD
Katherine Pierce MD
Aaron Morrison MD
Marcia Swanson DDS

Yolanda Harris DVM
Roger Forbes PhD
Tiffany Harmon
Mrs. Kimberly Brandt
Mr. Casey Pham
Mrs. Dana Hammond DDS
John Ruiz DDS
David Li MD
Lisa Velasquez MD
Brian Bryan MD
Mr. Brian Wilson
Mr. Joseph Medina
Monica Dean DDS
Travis Mcintyre DVM
Mrs. Kelsey Marshall
Mr. Duane Roberts MD
Jon Flores II
Mrs. Lisa Lyons MD
Philip Jones Jr.
Greg Joyce Jr.
Ms. Barbara Tran
Mrs. Mary Duarte MD
Christina Hull MD
Mr. Anthony Wilson
Mrs. Lisa Baker
Miss Mary Sloan
Mr. Joshua King
Daniel Mckinney MD
Nicole Martinez MD
David Robinson DVM
Joe Butler MD
Thomas Frye Jr.
Patrick Mcdaniel PhD
Brooke Williams
Robert Edwards PhD
Cynthia Mclaughlin PhD
Mark Hardy DDS
Kathryn Riley
Mrs. Heather Price
Miss Ashley Howell
Mr. James Adams
Mr. Michael Eaton
Mr. Joseph Marquez Jr.
Danielle Mercer DVM
Jacqueline York DDS
Mrs. Barbara Sanchez
Valerie Kline
Mr. Tony Cobb
Mr. Justin Jarvis
Nichole Novak MD
Mr. Matthew Cameron
Michael Robinson DVM
Adam Munoz PhD
Mr. Stephen Vaughan
Mr. Daniel Hale
Valerie Mccormick MD
Robert Smith Jr.
David Beck Jr.
Dana Bennett DVM
Tina Woodard
James Smith MD
Mr. Jerry Norton
Billy Hall DDS
Lauren Robertson MD
Mrs. Joyce Cunningham
Mr. Matthew Reilly
Erik Lowe MD
Mrs. Tara Lee
Theresa Gaines MD
Danielle Brown MD
Miss Misty Wood
Jonathan Maldonado MD
Mrs. Ashley Martin
Ms. Emily Ford
Mr. Isaiah Martinez DDS
Christopher Moore PhD
Mr. Andrew Robinson
Mr. Ryan Gates
John Fitzgerald MD
Gail Page PhD
Cheryl Richards MD
Todd Sandoval DVM
Mr. Brendan Watson
Mr. Brandon Bryan
Mrs. Karen Wright MD
Rhonda Stevenson MD
Danielle Cook MD
Ms. Taylor Velazquez
Michelle Porter DDS
Ryan Gomez II
Mrs. Rachel Hensley
Mrs. Cynthia Lawrence
Melissa Gonzalez DVM
Laura Tyler
Erik Smith Jr.
Angie Clarke DVM
Jennifer Olson MD
Omar Thompson Jr.
William Smith DDS
Jessica Smith DVM
Mr. Justin Mccoy
Robert Nguyen DDS
Leonard Roberts Jr.
Paul Johnson
Cody Martinez DVM
Duane Li Jr.
Ms. Allison Cunningham
Robert Hurley
Mrs. Ashley Floyd
Hunter James DDS
Brianna Greene MD
Matthew Higgins PhD
Mr. Jeremy Valentine
Wesley Martinez DDS
Mr. Justin Jones
Brent Ball DDS
Miss Jessica Holloway DVM
Mark Sanders MD
Tracy Levy
Larry Anderson MD
Steven Smith
Christian Hurst PhD
Amanda Gomez DDS
Mr. Anthony Nunez
Mrs. Rachel Newman DDS
Mr. Tyler Foster
Mr. Barry Copeland
Mr. Richard Edwards
Carly Montoya DDS
Mrs. Amy Bradford DDS
Mr. Tyler Allen
Mrs. Melissa Ramirez
Claudia Cook MD
Thomas Herrera DVM
Mr. Bobby Tucker
Stephanie Gonzalez
Bridget Hart DVM
Emily Graham DVM
Mr. Daniel Carpenter
Mr. Christian Bennett
Mr. Mark Peters DDS
Bradley Jackson
Miss Hannah Moore MD
Kaitlyn Adams MD
Darren Moore MD
Richard Lucero Jr.
Elizabeth Holder PhD
Mrs. Shannon Gonzalez MD
Seth Medina Jr.
Betty Raymond DVM
Crystal Watson
Scott Diaz DDS
Mrs. Lindsey White
Ryan Lamb DVM
Amber Graham MD
Mrs. Jennifer Chavez DVM
Becky Aguilar MD
Mrs. Lisa Vargas DDS
Robert Frazier DDS
Mrs. Jennifer Kelly
Mr. Richard Curry PhD
Mrs. Anna Perez
Keith Gomez DDS
Anthony Carlson Jr.
Bradley Rodgers
Mr. William Bishop
Mrs. Rhonda Bradley
Kimberly Martin DDS
Ryan Martinez MD
Latasha Thomas MD
Mrs. Tamara Burns
Andrea Dawson MD
Mr. Daniel Johnson
Lauren Smith MD
Nicole Brady
Wyatt Hoffman DDS
Kathy Bailey
Mr. Jorge Smith
Katherine Pham
Deanna Key DVM
Donna Mcclure MD
Jeremy Davis
Mrs. Brittany Boone MD
Debra Torres PhD
Hannah Garcia MD
Ms. Jacqueline Stone
Wesley Lynch MD
Edward Dudley II
Nathan Gonzalez MD
Sean Neal
Matthew Lewis Jr.
Jacob Perez PhD
Alexander Brown MD
Mr. Duane Sherman
Mr. John Petty
Ms. Brooke Stewart
Isaac Smith PhD
Kristi Soto MD
Timothy Haynes
Raven Ortiz MD
Kendra Buckley DDS
Mr. Russell Daniel
Christopher Bowers Jr.
Wendy Arroyo PhD
Taylor Hill DDS
Mrs. Lisa Guerrero
Mr. Jose Moran
Allison Perkins MD
Lisa Monroe DDS
Kenneth Cervantes DDS
Sandra Freeman MD
Mr. Patrick Rodriguez MD
Brendan Kim MD
Timothy Hughes Jr.
Carlos Mcdonald
Chad Bryant DDS
Gina Nguyen DDS
James Myers
Meagan Browning MD
Mr. Frank Delgado
Michael Torres MD
Michelle Richards MD
Kimberly Osborn MD
Kevin Hoover IV
Mr. Jeffrey Thompson
Mrs. Laurie Hamilton
David Butler Jr.
Amy Jones MD
Nicholas Frost DDS
Mr. James Thompson MD
Mrs. Adrienne Evans DDS
Mr. Christopher Bell
Louis Smith MD
Cameron Anderson
Crystal Wiggins MD
Michael Wilson Jr.
Matthew Savage MD
Jeffrey Jones DVM
Mr. John Burns
Luke Torres DVM
Christopher Stewart DVM
Benjamin Carlson MD
Emily Fitzgerald MD
Mrs. Carolyn Cole
Bruce Cummings DVM
Lisa Vance DVM
Mrs. Lisa Doyle
Brenda Sandoval
Miss Taylor Garza
Elizabeth Robinson PhD
Mr. George Hess Jr.
Courtney Cox PhD
Mr. Brian Schmidt DVM
Kevin Briggs Jr.
Ms. Grace Austin
Louis Cooper MD
Mrs. Tabitha Coleman
Thomas Knox MD
Sierra Little DDS
Mr. Joseph Matthews III
Mrs. Brenda Henderson DVM
Michael Martin DDS
Mr. Andrew Dennis
Edward Davenport
Dylan Bailey Jr.
Mr. John Jackson
Lisa Hernandez MD
Michael Gibbs
Angel Brown MD
Mr. Timothy Carter
Anthony Woods Jr.
Ms. Amy Watson
Marcus Jones MD
Kelsey Bennett MD
Ashley Wells DVM
Michael Harris Jr.
Daniel Diaz Jr.
Mrs. April Thornton
Steven Reid DDS
Mr. Jay Maxwell
Patrick Rasmussen
Jordan Smith
Cristian Williams PhD
Mrs. Amanda Harris DDS
Sean Reed DDS
Robin Higgins
Megan Glass
Mr. William Scott
Mr. Chad Gentry DDS
Taylor Thompson Jr.
Miss Wendy Martin
Daniel Robinson Jr.
Miss Jessica Hood
Michael Taylor MD
Micheal Stout DVM
Michael Aguirre DDS
Karl Campbell
Mr. Aaron Randolph
Jenna Arellano MD
Holly Adams MD
Melissa Barnett PhD
Brenda Brown DDS
Alicia Palmer MD
Carl Haynes
Anthony Bryant DDS
Christopher Perez DVM
Mrs. Amber Garner DVM
Thomas Diaz MD
Mr. Logan Thomas
Sherry Turner DDS
Joshua Martinez MD
Mrs. Alicia Sanford
Mrs. Laura Sexton
Melissa Coleman MD
Dana Burnett MD
Ronald Phelps Jr.
Mrs. Jessica Flynn
Robin Jones
Mr. Michael Jones
Jeffrey Parker MD
Mrs. Elizabeth Jones
Erika Stafford DVM
Mr. Vincent Reed
Mr. Justin Mcgee
Todd Turner DDS
Karen Kidd MD
Michael Miller PhD
Deborah Farrell
Mrs. Sharon Kelley
Andrew Cole MD
Jonathan Reid II
Mrs. Taylor Castillo
Joshua Smith Jr.
Joseph Herrera III
Miss Megan Smith
Catherine Ferguson MD
Mitchell Hays
Mrs. Jordan Turner
Mr. Robert Reyes
Mr. Johnny Walsh
Andrew Walsh PhD
Mrs. Lauren Collins
Adam Thompson MD
Mrs. Chelsea Roberts MD
Ms. Debra Brown
Vicki Santos PhD
Tony Robertson II
Kathleen Golden DDS
Elizabeth Tran
Miss Rachel West
Jessica Hoover DVM
Toni Graham DDS
Joseph Patel MD
Nathaniel Molina DDS
Ms. Cheryl Fisher
Nicolas Crawford MD
Wendy Owens DVM
Patricia Boone MD
Mr. Robert Estrada
Mr. Kevin Yates
James Fowler III
Andrea Welch DDS
Ms. Sara Parker
Destiny Mcdonald
Mrs. Brittany Perry MD
Timothy Mccoy DVM
Melissa Cohen MD
William Wright II
Jose White
Mason Graves
Diane Rodriguez
Marilyn Rubio DDS
Jose Lewis MD
Latasha Hughes MD
Monica Wallace DDS
Robin Reed
Ashley Butler
Misty Garcia MD
Amy Turner MD
Robert Miller DVM
Andrea Horton MD
Thomas Estes MD
Justin Warner MD
Thomas Carrillo II
James Hess DDS
Matthew Bennett Jr.
John Scott MD
Mrs. Carla Lawson
Anthony Campbell DDS
Mario Griffith MD
Mr. Jacob Jackson
Mrs. Allison Robinson
Mrs. Amber Hall
Miss Gabriela Burch
Kathryn Wade MD
Mr. Anthony Martinez
Justin Duffy
Steven Hoover MD
Mary Smith MD
Tiffany Young DDS
Mark Lucas IV
Kenneth Marquez MD
Keith Newman Jr.
Matthew Mitchell III
Jo Williams
Lauren Howell DDS
Erica Martin DDS
Ms. Hannah Mcdonald MD
Brandon Palmer DDS
Ms. Stephanie Nichols DVM
Mckenzie Cummings
Valerie Joseph DVM
Harold Parker PhD
Mr. David Reeves
Christina Barrera
Kristen Solis MD
Colin Schultz II
Miss Michelle Li
Mr. Andrew Summers
Kimberly Ramos
Thomas Meyer DVM
Troy Foster MD
John Hernandez DVM
Valerie Krueger DDS
Carol Valdez DDS
Jay Johnson DDS
Brenda Holloway DVM
Wendy Parker MD
Kim Smith DVM
Mr. Wesley Fields MD
Nicole White MD
Amanda Skinner MD
Adrienne Turner MD
Terry Scott Jr.
Cesar Rodriguez DVM
Jennifer Gay MD
Mr. Earl Thompson
Miss Melinda Thomas
Mary Nixon MD
Leslie Kelly MD
Mrs. Kristen Gonzalez
Michael Carter MD
Joseph Perez DDS
Mrs. Alice Warren
Julia Kelley MD
David Coffey PhD
Mrs. Pam Wolf DDS
Mr. Ryan Thomas
Gregory Morgan MD
Carol Williams
Ms. Rebecca Gonzales
Mrs. Samantha Glover
Anna Decker MD
Hailey Lopez DDS
Mr. James Baker
Mrs. Amber Gonzalez
Mr. Jason Patel Jr.
Stephanie Walker DDS
Mr. Timothy Scott
Michael Sullivan DDS
Mrs. Brittney Schultz DVM
Frances Romero
Laura Bennett DDS
Allen Goodwin DDS
Kimberly Brown MD
Steven Lewis Jr.
Angela Garcia DDS
William Foster PhD
Lucas Williams Jr.
Kimberly Page
Deborah Higgins DDS

In [25]:
# Add each prefix and suffix to remove to a list.
prefixes_suffixes = ["Dr. ", "Mr. ","Ms. ", "Mrs. ", "Miss ", " MD", " DDS", " DVM", " PhD"]

# Iterate through the "prefixes_suffixes" list and replace them with an empty space, "" when it appears in the student's name.
for word in prefixes_suffixes:
    student_data_df["student_name"] = student_data_df["student_name"].str.replace(word,"")

##student_data_df["student_name"].tail(20)

# Put the cleaned students' names in another list.
student_names = student_data_df["student_name"].tolist()
student_names

['Paul Bradley',
 'Victor Smith',
 'Kevin Rodriguez',
 'Richard Scott',
 'Bonnie Ray',
 'Bryan Miranda',
 'Sheena Carter',
 'Nicole Baker',
 'Michael Roth',
 'Matthew Greene',
 'Andrew Alexander',
 'Daniel Cooper',
 'Brittney Walker',
 'William Long',
 'Tammy Hebert',
 'Jordan Carson',
 'Donald Zamora',
 'Kimberly Santiago',
 'Kevin Stevens',
 'Brandi Lyons',
 'Lisa Davis',
 'Kristen Lopez',
 'Kimberly Stewart',
 'Christopher Parker',
 'Chelsea Griffith',
 'Cesar Morris',
 'Melanie Decker',
 'Tracey Oconnor',
 'Kelly James',
 'Nicole Brown',
 'Bobby Harris',
 'Brian Fernandez',
 'Candace Phelps',
 'Amy Gonzalez',
 'Steven Green',
 'Benjamin Carlson',
 'Kevin Bailey',
 'Jesse Newton',
 'Kimberly Mercado',
 'Gregory Roberts',
 'Matthew Mayer',
 'Jennifer Parks',
 'John Carlson',
 'Megan Roberts',
 'Debra Flores',
 'Heidi Jackson',
 'Denise Bradford',
 'Ellen Brown',
 'Amy Perkins',
 'Natalie Mitchell',
 'Tiffany Gutierrez',
 'Jennifer Hess',
 'Christine Fletcher',
 'Jon Smith',
 'Tracey Yates',
 'Jerry Gordon',
 'Michael Cox',
 'Madeline Snyder',
 'Allison King',
 'Theresa Meyer',
 'Jared Wood',
 'Eric Maynard',
 'Mark Owens',
 'Ronnie Conley',
 'Kimberly Davis',
 'Amy Mitchell',
 'Dylan Taylor',
 'Elizabeth Henderson',
 'James Lopez',
 'Michael Morgan',
 'Angela Francis',
 'Breanna Taylor',
 'Jason Johnson',
 'Kyle Martin',
 'Scott Gill',
 'Lisa Long',
 'Erin Liu',
 'Marcus Richards',
 'Jason Thompson',
 'Elizabeth Mckinney',
 'Jessica Bailey',
 'Lisa Frye',
 'Lindsey Baker',
 'Lisa Ramirez',
 'Joseph Butler',
 'Tina Lynch',
 'Leah Benitez',
 'Elizabeth Parker',
 'Melissa Hunter',
 'Madison Everett',
 'Ronald Garcia',
 'Mark Cherry',
 'Ryan Stokes',
 'Isaiah Maldonado',
 'Micheal Dennis',
 'Kevin Martinez',
 'Jessica Smith',
 'Dawn Trujillo',
 'Virginia Ramirez',
 'Marc Hernandez',
 'Jose Gonzalez',
 'Jason Dennis',
 'Gary Morris',
 'William Mcdonald',
 'Michael Savage',
 'Alexis Todd',
 'David Hansen',
 'Steven Mendez',
 'Ryan Lynch',
 'Timothy Marks',
 'Alexander Johns',
 'Kenneth Chavez',
 'Dennis Williams',
 'Michael Roy',
 'Richard Ryan',
 'Matthew Reyes',
 'Stephanie Ward',
 'Christopher Tucker',
 'Daniel Jones',
 'Devin Craig',
 'Erin Prince',
 'Bernard Ortiz',
 'Nicole Miller',
 'Christopher Fritz',
 'Bonnie Mckinney',
 'Troy Nelson',
 'Jennifer Lee',
 'Ronald Ward',
 'Nathaniel Hampton',
 'Michael Travis',
 'James Taylor',
 'Thomas Strickland',
 'Brittany Jackson',
 'Marisa Lowe',
 'Nicole Thomas',
 'Matthew Rodriguez',
 'Kent Fernandez',
 'Michelle Martin',
 'John Sparks',
 'Ann Blake',
 'Melissa Miller',
 'Steven Houston',
 'Kristen Anderson',
 'Cory Jones',
 'Jennifer Mora',
 'Dennis Griffin',
 'Darryl Brown',
 'Martin Mosley',
 'Joyce Diaz',
 'Jeffrey Rose',
 'Jamie Moreno',
 'Catherine Williams',
 'Lauren Byrd',
 'Vanessa Frazier',
 'Stephen Bryant',
 'Lawrence Liu',
 'Joseph Larsen',
 'Susan Collier',
 'Meagan Jensen',
 'Julie Harper',
 'Meghan Carroll',
 'Wanda Horton',
 'Mary Campbell',
 'Jennifer Rodgers',
 'Heather Cooper',
 'Ryan Perez',
 'Ryan Cox',
 'Darren Zavala',
 'Joseph Morales III',
 'Aaron West',
 'James Combs',
 'Curtis Garner',
 'Sarah Miller',
 'Samantha Thomas',
 'Robert Atkins',
 'Alexis Crawford',
 'Ryan Maddox',
 'Jonathan Meyer',
 'Donna Wagner',
 'William Kennedy',
 'Kimberly Martinez',
 'Matthew Anderson',
 'Kari Miller',
 'Jenna Luna',
 'Justin Contreras',
 'Mary Fox',
 'Joseph Perkins',
 'Kelly Phillips',
 'Justin Thornton',
 'Joshua Barber',
 'Travis Jackson',
 'Jordan Beasley',
 'Kevin Allen',
 'Victoria Harris',
 'Victoria Joseph',
 'Brandy Marshall',
 'Ryan Jimenez',
 'Michael Chan',
 'Christopher Phillips',
 'Kevin Murphy',
 'Vanessa Harper',
 'James Ferguson',
 'Carol Schroeder',
 'Jerry Phillips',
 'Kristin Wade',
 'Jessica Warner',
 'Dorothy Burke',
 'Bethany Walter',
 'Melissa Avery',
 'Daniel Sutton',
 'Ryan Johnson',
 'Timothy Quinn',
 'Zachary Allen',
 'Lauren Schmitt',
 'Stephanie Armstrong',
 'Ruben Rivera',
 'Patricia Petty',
 'Joseph Jacobs',
 'Bianca Wilson',
 'Donald Perez',
 'Curtis Gomez',
 'Courtney Brown',
 'Nicole Randall',
 'Steven Lambert',
 'Anthony Alvarez',
 'Shawn Farrell',
 'Jesus Schmidt',
 'Laura Wright',
 'Steven Smith',
 'Norman Thompson',
 'Anthony Wright',
 'Kayla Watts',
 'Aimee Johnson',
 'Heidi Scott',
 'Anthony Williams',
 'Sarah Hill',
 'Kim Wang',
 'Beth Manning',
 'Ryan Hanson',
 'James Wood',
 'Corey Greene',
 'John Carter',
 'Beth Garza',
 'Karen Jones',
 'Stephanie Poole',
 'Lisa Brown',
 'Paul Scott',
 'Evelyn Buck',
 'Terry Harrell',
 'Leah Skinner',
 'Anthony Mercado',
 'Walter Kelly',
 'Lori Evans',
 'Ashley Jones',
 'Amber Soto',
 'Patrick Phillips',
 'Linda Curry',
 'Alexander Obrien',
 'Vincent Garza',
 'Terry Marsh',
 'Angela Perkins',
 'Peter Hampton',
 'David Cross',
 'Clinton Ortega',
 'Jamie Escobar',
 'Sandra Mason',
 'Craig Cole',
 'Lisa Warren',
 'Maria Howard',
 'Michael Porter',
 'John Turner',
 'Timothy Wang',
 'Amanda Taylor',
 'Karen Mckenzie',
 'Brandon Miles',
 'Christina Whitaker',
 'Nicole Peterson',
 'Ashley Moore',
 'Todd Carrillo',
 'Robert Williams',
 'Ashley Jones',
 'Vanessa Parker',
 'Robert Carlson',
 'Jared Lewis',
 'Christopher Hernandez',
 'Kimberly Harris',
 'Katrina Hill',
 'Heather Lee',
 'Donald Harmon',
 'Elizabeth Sanders',
 'Richard Ramsey',
 'Carmen Johnson',
 'Elaine Osborne',
 'Kent Burns',
 'Meagan Smith',
 'Craig Hahn',
 'Jeremy Wu',
 'Aaron Rodriguez',
 'Matthew Taylor',
 'Diana Evans',
 'Michele Pearson',
 'Erik Wagner',
 'Maria Welch',
 'Debra Martin',
 'Devon Conner',
 'Christine Patel',
 'David Lopez',
 'Nathan Baird',
 'Samuel Castillo',
 'Rebecca Payne',
 'Carl Johnson',
 'William Adams',
 'Paula Harrison',
 'Wayne Atkinson',
 'Lindsay Frank',
 'Jose Garcia',
 'Andrew Gaines',
 'Rachael Liu',
 'Donald Lewis',
 'Shane Edwards',
 'Todd Levy',
 'Joanna Moore',
 'Michael Lewis',
 'James Robinson',
 'Jeffrey Arellano',
 'Heather Allen',
 'Lori Villarreal',
 'Robert Harper',
 'Karen Villegas',
 'Tracey Crane',
 'Elizabeth Allen',
 'Jorge Lynn',
 'Harold Gordon',
 'Nicholas Mcclain',
 'Tanya Harris',
 'Amy Smith',
 'Kathy Morse',
 'Andrea Wood',
 'Maureen Massey',
 'Daniel Smith',
 'Alexandra Smith',
 'Caitlin Hall',
 'Jose Carlson',
 'Deborah Macias',
 'Dwayne Rice',
 'Matthew Harris',
 'Eric Bowman',
 'Samuel Ali',
 'David Miller',
 'James Moreno',
 'Brooke Austin',
 'Alisha Martin',
 'Neil Rodriguez',
 'Gary Williams',
 'Michael Pittman',
 'Stephanie Palmer',
 'Christine Perry',
 'Suzanne David',
 'Amber Smith',
 'Ryan Jones',
 'Emily Ford',
 'Kelsey Shea',
 'Katherine Wallace',
 'Erica Conway',
 'Tyler Parker',
 'Michael Parks',
 'Elizabeth Hunt',
 'Grant Jackson',
 'Daniel Matthews',
 'Diana Silva',
 'Frank Garza',
 'Terri Fischer',
 'Robert Goodwin',
 'Bobby Ruiz',
 'Stephanie Taylor',
 'Erin Hill',
 'Erin Cohen',
 'Jeffrey Morris',
 'Elizabeth Simpson',
 'Jennifer Davis',
 'Rachel Burton',
 'Joseph Wilkins',
 'Lawrence Montgomery',
 'Patricia Howard',
 'Jessica Hanson',
 'Donna Dean',
 'Edwin Reid',
 'Jodi Brown',
 'Elizabeth Richard',
 'Aaron Martinez',
 'Stephen Fischer',
 'Diana Reeves',
 'Jeffrey Eaton',
 'Evelyn Miller',
 'Christopher Kidd',
 'Sarah Adams',
 'Melinda Nelson',
 'Kevin Brooks',
 'John Bowen',
 'Tracie Abbott',
 'Allen Foster',
 'Kathryn Elliott',
 'Christopher Walker',
 'Cynthia Martin',
 'Amanda Bennett',
 'Dennis Padilla',
 'Antonio Miller',
 'Melissa Trevino',
 'Andrew King',
 'John Martinez',
 'Lauren King',
 'Stephanie Mercado',
 'William Smith',
 'Jonathan Marshall',
 'Luke Lowery',
 'Emily Reynolds',
 'Kevin Mclean',
 'Elizabeth Taylor',
 'Pamela Rivas',
 'Tammy Martin',
 'Holly Watkins',
 'Patrick Chen',
 'Michelle Griffin',
 'Theresa Andrews',
 'Alan Henry',
 'Larry Hines',
 'Travis Frazier',
 'Julie Jones',
 'Natalie Reynolds',
 'Jessica Cohen',
 'Jason Robinson',
 'Heather Palmer',
 'Emily Cardenas',
 'Scott Glover',
 'Jacqueline White',
 'Elizabeth Espinoza',
 'Toni Porter',
 'Jennifer Mejia',
 'Brenda Peterson',
 'Paul Hamilton',
 'Patricia Nguyen',
 'James Ho',
 'Elizabeth Cohen',
 'Stephanie Lane',
 'Dawn Rhodes',
 'Theresa Robinson',
 'Breanna Mosley',
 'Carmen Wilson',
 'Ian Brown',
 'Kathleen Matthews',
 'Bryan Diaz',
 'Gina Sweeney',
 'Alan Garcia',
 'Erik Wheeler',
 'Stephanie Robles',
 'Samantha Hanson',
 'Christopher Williams',
 'Stephanie Hart',
 'Lisa Becker',
 'Bianca Johnson',
 'Amy Steele',
 'Gina Contreras',
 'Jaime Alexander',
 'Kevin Coleman',
 'Caitlin Williams',
 'Joseph Lloyd',
 'Carrie Hernandez',
 'Travis Young',
 'Francis Wright',
 'Joel Harper',
 'Eduardo Park',
 'Melissa Yoder',
 'Donna Campbell',
 'Connie Delacruz',
 'Luis Parker',
 'Pamela Watts',
 'Lindsey Mitchell',
 'Brenda Price',
 'Joseph Howard',
 'Amy Evans',
 'Paula Fernandez',
 'Amber Cunningham',
 'Preston Wheeler',
 'James Lopez',
 'Chad Drake',
 'Samuel Blackburn',
 'Shawn Nielsen',
 'Eric Perez',
 'Kevin Montgomery',
 'Terry Thomas',
 'Kim Meyer',
 'Michael Townsend',
 'Ronnie Rodriguez',
 'Savannah Smith',
 'Shane Nguyen',
 'Michael Brown',
 'Robert Young',
 'Daniel Griffin',
 'James Johnson',
 'Mary Cox',
 'Tina Aguirre',
 'Jillian Mcdonald',
 'Matthew Branch',
 'Christopher Jordan',
 'Victor Mcguire',
 'Erin Arnold',
 'Nicholas Wu',
 'Kristen Wilson',
 'Morgan Moore',
 'Stephen Smith',
 'Jeremy Romero',
 'Julie Bush',
 'Brittany Taylor',
 'James Kim',
 'Ashley Roberts',
 'Brandon Johnson',
 'David Davenport',
 'Mark Washington',
 'Alicia Marshall',
 'Barbara Santana',
 'Samantha Parker',
 'Joseph Walters',
 'Michael Zamora',
 'Kyle Cobb',
 'Jill Clark',
 'Sarah Warren',
 'Jennifer Robinson',
 'Patricia Johnson',
 'Henry Evans',
 'Alexander Ramsey',
 'Brandon Stephens',
 'Jeff Holland',
 'Samuel Schultz',
 'Brett Johnson',
 'Daniel Sherman',
 'Justin Mccall',
 'Jonathan Evans',
 'Jacqueline Kennedy',
 'Martin Stephenson',
 'Lindsey Lane',
 'Jessica Hart',
 'Edward Lucas',
 'Lisa Osborne',
 'Hannah Black',
 'Alexander Paul',
 'Brenda Wong',
 'Thomas Delgado',
 'Jeremy Sutton',
 'Paula Donaldson',
 'Valerie Thompson',
 'John Schaefer',
 'Jesus Manning',
 'Tyrone Lawson',
 'Carl May',
 'Brittany Russell',
 'Philip Edwards',
 'Robert Aguilar',
 'Aaron Russo',
 'Tracy Andrade',
 'Amy Sullivan',
 'Howard Beck',
 'Xavier Bell II',
 'Dawn Schultz',
 'Caleb Lucas',
 'Barbara Gonzalez',
 'Charles Yang',
 'David Gallagher',
 'Bethany Vargas',
 'Jennifer Schultz',
 'Paula Marshall',
 'Jordan Elliott',
 'Samantha Mcmillan',
 'Judith Johnson',
 'Grace Palmer',
 'Brandon Ramirez',
 'Carol Smith',
 'Matthew Odom',
 'Erika Gray',
 'Donna Kramer',
 'Jonathan Snyder',
 'Frank Howe',
 'Amy Beck',
 'Lori Holmes',
 'Rebekah Hampton',
 'Perry Bishop',
 'Andrew Hanson',
 'Jody Hughes',
 'Anna Garcia',
 'Colleen Walker',
 'Danny Bridges',
 'Kristina Ford',
 'Sabrina Davidson',
 'Alexander Freeman',
 'Jack Davis',
 'Victor Rivera',
 'Elizabeth Pena',
 'Neil Castro',
 'Michael Briggs',
 'Anna Andersen',
 'Elizabeth Oconnor',
 'Zachary Brooks',
 'Scott Jackson',
 'Mary Fuentes',
 'Denise Reyes',
 'Janice Collier',
 'Tina Barber',
 'Keith Rojas',
 'Michelle Decker',
 'James Smith',
 'Alexandra Thompson',
 'Jacqueline Campbell',
 'Austin Clark',
 'Brooke Thomas',
 'Molly Smith',
 'Pamela Beck',
 'Timothy Morris',
 'Lauren White',
 'Jessica Beltran',
 'Alexandra Jones',
 'Evelyn Rice',
 'Stephen Ellis',
 'Caroline Smith',
 'Fred Case',
 'Crystal Anderson',
 'Jordan Gross',
 'Marie Harris',
 'Charles Hayes',
 'Beverly Sheppard',
 'Denise Solis',
 'Alexander Myers',
 'Sally Robertson',
 'Steven Morris',
 'Nina Flores',
 'Miguel Patterson',
 'John Simpson',
 'Charles Cruz',
 'Monica Davis',
 'James Fields',
 'Kevin Frederick',
 'Jeremy Soto',
 'Ronald Harris',
 'Carol Stewart',
 'Albert Durham',
 'James Sanchez',
 'John Adams',
 'Cody Williams',
 'Ernest Love',
 'Tommy Smith',
 'Jared Anderson',
 'Jennifer Yang',
 'Joe Mercado',
 'Roberto Wright',
 'Michael Smith',
 'William Park',
 'Benjamin Williams',
 'Dean Perez',
 'Dale Miller',
 'Marissa Russell',
 'Mary Gonzalez',
 'April Jackson',
 'William Hayes',
 'Meghan Holloway',
 'Amy Coleman',
 'James Green',
 'Michael Tran',
 'Joseph Cortez',
 'Anita Moss',
 'Benjamin Stokes',
 'Michael Li',
 'Alexander Rosales',
 'Katie Dawson',
 'Shelly Erickson',
 'Kathryn Turner',
 'Jacob Lee',
 'Ryan Smith',
 'Joshua Fernandez',
 'Mia Roach',
 'William Rodriguez',
 'Wanda Cruz',
 'Pamela Hall',
 'David Smith',
 'Jason Brown',
 'Chelsea Alexander',
 'Kimberly Tate',
 'Daniel Williams',
 'Terri Jacobson',
 'Paul Harris',
 'Jessica Thompson',
 'Nancy Hawkins',
 'Deborah Phillips',
 'Mark Mendoza',
 'Stephen Williamson',
 'Jennifer Strong',
 'Matthew Moore',
 'Raymond Parker',
 'Lee Evans',
 'Curtis Rodriguez',
 'Sara Morris',
 'Dawn Palmer',
 'Brianna Benson',
 'Luis Watts',
 'Cindy Brown',
 'Summer Sandoval',
 'Ashley Smith',
 'Randy Wallace',
 'Angela Simmons',
 'Sandra Haley',
 'George Morgan',
 'Melissa Ali',
 'Matthew Oliver',
 'Michael Kirk',
 'Terry Khan',
 'Kristie Elliott',
 'Joel Campbell',
 'Anthony Henderson',
 'Brent Christensen',
 'Heidi Hayes',
 'Ryan Mcbride',
 'Kyle Murillo',
 'Angela Powell',
 'Jeanette Simmons',
 'Adam Vance',
 'Kristen Murray',
 'Jessica Burnett',
 'Alex Walker',
 'Robert Phillips',
 'Elizabeth Martinez',
 'Kristina Young',
 'Sarah Morgan',
 'Cheryl Harding',
 'Keith Hunter',
 'Todd Williams',
 'James White',
 'Kyle Johnson',
 'Andrea Suarez',
 'Michael Sanchez',
 'Jaime Torres',
 'Donald Gill',
 'Austin Lee',
 'Adrian Bowman',
 'Julie Perez',
 'Debra Maxwell',
 'Bradley Phillips',
 'Sonya Simmons',
 'Eric Miller',
 'Charles Berger',
 'Mary Monroe',
 'Destiny Burns',
 'Patrick Khan',
 'Nathaniel Henson',
 'Larry Miller',
 'Timothy French',
 'Xavier Mitchell',
 'Jason Crosby',
 'Joshua Johnson',
 'Alyssa Clark',
 'Jonathan Cooper',
 'Mark Hunt',
 'Norman Moore',
 'Brian Atkins',
 'Zachary Jones',
 'Danielle Wong',
 'Patricia Lane',
 'Joshua Rose',
 'Hannah Montes',
 'Catherine Williams',
 'Michael Jenkins',
 'James Scott',
 'Evan Ballard',
 'Andrea Miller',
 'Jasmine Lynch',
 'Jennifer Fox',
 'Jared Castro',
 'Eugene Cox',
 'Wendy Wilson',
 'Debbie Smith',
 'Michael Fletcher',
 'Jay Waters',
 'Melissa Martinez',
 'Cory Howard',
 'Mitchell Hanson',
 'Corey Boyer',
 'Elizabeth Gonzalez',
 'Robert Hutchinson',
 'David Hernandez',
 'Tammy Jordan',
 'Denise Johnson',
 'Brandi Copeland',
 'Evan Marshall',
 'Gregory Long',
 'Kristen Underwood',
 'Walter French',
 'Edwin Thompson',
 'Edward Rivera',
 'Brandon Wilson',
 'Alejandra Todd',
 'Dana Hoffman',
 'David Howard',
 'Ashley Caldwell',
 'Cindy Horn',
 'Kevin Armstrong',
 'Stacey Porter',
 'Patrick Hunt',
 'David White',
 'Tammy Black',
 'Joanna Williams',
 'Becky Moran',
 'Brenda Smith',
 'Gabrielle Webb',
 'Jared Campbell',
 'Ryan Jenkins',
 'Thomas Shepard',
 'Jeremiah Boyd',
 'Matthew White',
 'Christina Anderson',
 'Edward Olson',
 'Emily Bryant',
 'Amy Guzman',
 'Kathleen Owens',
 'John Davila',
 'Nicole King',
 'Jason Villarreal',
 'Matthew Washington',
 'Peter Simpson',
 'Cristian Espinoza',
 'Steven Fry',
 'David Miller',
 'Tamara Hernandez',
 'Jordan Lewis',
 'Carol Anderson',
 'Michael Moreno',
 'Nicholas Logan',
 'Paul Anderson',
 'Jason Young',
 'Wesley Martin',
 'Karen Wall',
 'Tara Parker',
 'Michael Reyes',
 'Amy Henderson',
 'Jessica Reed',
 'Joseph Miranda',
 'Mackenzie Jones',
 'Jon Espinoza',
 'Kelly Medina',
 'Jason Rubio',
 'Jennifer Munoz',
 'Christopher Warner',
 'Vincent Thomas',
 'Andrew Young',
 'David Jenkins',
 'Daniel Stephens',
 'Elizabeth Lewis',
 'Aaron Moore',
 'Lisa Hogan',
 'Shawn Williams',
 'Michele Dickerson',
 'Alicia Martinez',
 'Timothy Anderson',
 'Sierra Jackson',
 'Sharon Taylor',
 'Jeffrey Smith',
 'Mark Taylor',
 'Christina Ross',
 'Judy Hall',
 'Jennifer Fox',
 'Kenneth Moran',
 'Gerald Ferguson',
 'Albert Carter',
 'Michael Reilly',
 'Kathleen Schwartz',
 'Stacey Harris',
 'Paula Lee',
 'Adrian Black',
 'Rita Moreno',
 'Jason Perry',
 'Scott Ortiz',
 'Randy Mueller',
 'Samantha Anderson',
 'Phillip Brown',
 'Christina Kerr',
 'Derrick Hill',
 'Nathan Bond',
 'Marie Wilson',
 'Caitlin Jones',
 'Barbara Campbell',
 'Katie Gonzales',
 'Elijah Hall',
 'James Sanders',
 'Nicholas Martinez',
 'Maria Mack',
 'Mary Mason',
 'Tiffany Campbell',
 'Raymond Stone',
 'Dominique Henderson',
 'Martin Williams',
 'Hannah Parker',
 'Susan Webb',
 'Rachel Johnson',
 'Darren Davis',
 'Tim Carr',
 'Jesus Ryan',
 'John Hays',
 'Scott Stewart',
 'Alexandra Roberts',
 'Amanda Norman',
 'James Moody',
 'Brenda Jones',
 'Kathy Smith',
 'Raymond Clark',
 'Ashley Martin',
 'Tamara Flowers',
 'Cesar Hanson',
 'Ross Strickland',
 'Randy Moore',
 'Henry Andersen',
 'Paul Martin',
 'Sarah Stanley',
 'Jordan Lewis',
 'Ashley Richardson',
 'Michael Brown',
 'Jason Davis',
 'Wendy Mcclain',
 'Troy Williams',
 'Carrie Alexander',
 'Kyle Ware',
 'Michael Robinson',
 'Roger Wilson',
 'Teresa Fuller',
 'Craig Silva',
 'Duane Thomas',
 'Jon Crosby',
 'Jon Steele',
 'Daniel Shaw',
 'Gwendolyn Williams',
 'Angela Hess',
 'Cameron Arnold',
 'Janice Garcia',
 'Anne Bullock',
 'Katie Moody',
 'Kayla Rivas',
 'Danny Pearson',
 'Billy Robles',
 'Michelle Delgado',
 'Cindy Harrison',
 'John Dickerson',
 'Tina Armstrong',
 'Alex Franklin',
 'Ryan King',
 'Christine Guzman',
 'Helen Malone',
 'Benjamin Carpenter',
 'Jessica Dunn',
 'Jessica Kaiser',
 'Brandon Black',
 'David Hernandez',
 'Brenda Turner',
 'Katherine Black',
 'Larry Santos',
 'Zachary Dominguez',
 'Tanya Fernandez',
 'Joseph Nichols',
 'Rebecca Martinez',
 'Traci Ramirez',
 'Ryan Bauer',
 'Joshua Williams',
 'Devon Foley',
 'Heidi Walter',
 'Mario Nguyen',
 'Jordan Hernandez',
 'William Miller',
 'Nicholas Chung',
 'Christine Cooley',
 'Carrie Nelson',
 'Crystal Fowler',
 'Lori Taylor',
 'Michael Stevenson',
 'Matthew Holmes',
 'David Walls',
 'Megan Martin',
 'Karen Peterson',
 'Kristen Wallace',
 'Mark Peterson',
 'Jason Jones',
 'Keith Barber',
 'Patrick Green',
 'Antonio Lopez',
 'Travis Peterson',
 'Gabriel Hunter',
 'Amanda Ross',
 'Samuel Thompson',
 'Robert Bowman',
 'Cynthia Cox',
 'Brittany Miller',
 'Eric Torres',
 'Sandra Calhoun',
 'Jacob Bailey',
 'Jessica Harris',
 'Molly Carr',
 'Keith Davis',
 'Adriana Wade',
 ...]

In [26]:
# Create a new list and use it for the for loop to iterate through the list.
students_fixed = []

# Use an if statement to check the length of the name.

# If the name is greater than or equal to 3, add the name to the list.

for name in student_names:
    if len(name.split()) >= 3:
        students_fixed.append(name)

# Get the length of the students' names that are greater than or equal to 3.
len(students_fixed)

151

In [27]:
# Combine the data into a single dataset.
school_data_complete_df = pd.merge(student_data_df, school_data_df, on=["school_name", "school_name"])
school_data_complete_df.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635

In [28]:
# Get the total number of students.
student_count = school_data_complete_df.count()
student_count

Student ID       39170
student_name     39170
gender           39170
grade            39170
school_name      39170
reading_score    39170
math_score       39170
School ID        39170
type             39170
size             39170
budget           39170
dtype: int64

In [29]:
# Calculate the total number of schools.
school_count = school_data_df["school_name"].count()
school_count

15

In [30]:
# Calculate the total number of schools
school_count_2 = len(school_data_complete_df["school_name"].unique())
school_count_2

15

In [31]:
# Calculate the total budget.
total_budget = school_data_df["budget"].sum()
total_budget

24649428

In [32]:
# Calculate the average reading score.
average_reading_score = school_data_complete_df["reading_score"].mean()
average_reading_score

81.87784018381414

In [33]:
# Calculate the average math score.
average_math_score = school_data_complete_df["math_score"].mean()
average_math_score

78.98537145774827

In [34]:
passing_math = school_data_complete_df["math_score"] >= 70
passing_reading = school_data_complete_df["reading_score"] >= 70

In [35]:
# Get all the students who are passing math in a new DataFrame.
passing_math = school_data_complete_df[school_data_complete_df["math_score"] >= 70]
#passing_math["student_name"].count()
len(passing_math)

29370

In [36]:
# Get all the students that are passing reading in a new DataFrame.
passing_reading = school_data_complete_df[school_data_complete_df["reading_score"] >= 70]
len(passing_reading)

33610

In [37]:
# Calculate the total number of schools.
student_count = student_data_df["Student ID"].count()

# Calculate the number of students passing math.
passing_math_count = passing_math["student_name"].count()

# Calculate the number of students passing reading.
passing_reading_count = passing_reading["student_name"].count()

# Calculate the percent that passed math.
passing_math_percentage = passing_math_count / float(student_count) * 100

# Calculate the percent that passed reading.
passing_reading_percentage = passing_reading_count / float(student_count) * 100

# Calculate the overall passing percentage.
overall_passing_percentage = (passing_math_percentage + passing_reading_percentage ) / 2

overall_passing_percentage

80.39315802910392

In [38]:
# Adding a list of values with keys to create a new DataFrame.
district_summary_df = pd.DataFrame(
          [{"Total Schools": school_count,
          "Total Students": student_count,
          "Total Budget": total_budget,
          "Average Math Score": average_math_score,
          "Average Reading Score": average_reading_score,
          "% Passing Math": passing_math_percentage,
         "% Passing Reading": passing_reading_percentage,
        "% Overall Passing": overall_passing_percentage}])
district_summary_df

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
0,15,39170,24649428,78.985371,81.87784,74.980853,85.805463,80.393158

In [39]:
# Format the "Total Students" to have the comma for a thousands separator.
district_summary_df["Total Students"] = district_summary_df["Total Students"].map("{:,}".format)

district_summary_df["Total Students"]

0    39,170
Name: Total Students, dtype: object

In [40]:
# Format the columns.
district_summary_df["Average Math Score"] = district_summary_df["Average Math Score"].map("{:.1f}".format)

district_summary_df["Average Reading Score"] = district_summary_df["Average Reading Score"].map("{:.1f}".format)

district_summary_df["% Passing Math"] = district_summary_df["% Passing Math"].map("{:.0f}".format)

district_summary_df["% Passing Reading"] = district_summary_df["% Passing Reading"].map("{:.0f}".format)

district_summary_df["% Overall Passing"] = district_summary_df["% Overall Passing"].map("{:.0f}".format)

In [41]:
# Reorder the columns in the order you want them to appear.
new_column_order = ["Total Schools", "Total Students", "Total Budget","Average Math Score", "Average Reading Score", "% Passing Math", "% Passing Reading", "% Overall Passing"]

# Assign district summary df the new column order.
district_summary_df = district_summary_df[new_column_order]
district_summary_df

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
0,15,"39,170",24649428,79.0,81.9,75,86,80

In [42]:
# Determine the school type.
per_school_types = school_data_df.set_index(["school_name"])["type"]
per_school_types

school_name
Huang High School        District
Figueroa High School     District
Shelton High School       Charter
Hernandez High School    District
Griffin High School       Charter
Wilson High School        Charter
Cabrera High School       Charter
Bailey High School       District
Holden High School        Charter
Pena High School          Charter
Wright High School        Charter
Rodriguez High School    District
Johnson High School      District
Ford High School         District
Thomas High School        Charter
Name: type, dtype: object

In [43]:
# Add the per_school_types into a DataFrame for testing.
df = pd.DataFrame(per_school_types)
df

                           type
school_name
Huang High School      District
Figueroa High School   District
Shelton High School     Charter
Hernandez High School  District
Griffin High School     Charter
Wilson High School      Charter
Cabrera High School     Charter
Bailey High School     District
Holden High School      Charter
Pena High School        Charter
Wright High School      Charter
Rodriguez High School  District
Johnson High School    District
Ford High School       District
Thomas High School      Charter

In [44]:
# Calculate the total student count.
per_school_counts = school_data_complete_df.set_index(["school_name"])["student_name"]
per_school_counts = per_school_counts.groupby(["school_name"]).count()
per_school_counts

school_name
Bailey High School       4976
Cabrera High School      1858
Figueroa High School     2949
Ford High School         2739
Griffin High School      1468
Hernandez High School    4635
Holden High School        427
Huang High School        2917
Johnson High School      4761
Pena High School          962
Rodriguez High School    3999
Shelton High School      1761
Thomas High School       1635
Wilson High School       2283
Wright High School       1800
Name: student_name, dtype: int64

In [45]:
# Calculate the total school budget.
per_school_budget = school_data_df.set_index(["school_name"])["budget"]
per_school_budget

school_name
Huang High School        1910635
Figueroa High School     1884411
Shelton High School      1056600
Hernandez High School    3022020
Griffin High School       917500
Wilson High School       1319574
Cabrera High School      1081356
Bailey High School       3124928
Holden High School        248087
Pena High School          585858
Wright High School       1049400
Rodriguez High School    2547363
Johnson High School      3094650
Ford High School         1763916
Thomas High School       1043130
Name: budget, dtype: int64

In [46]:
# Calculate the per capita spending.
per_school_capita = per_school_budget / per_school_counts
per_school_capita

school_name
Bailey High School       628.0
Cabrera High School      582.0
Figueroa High School     639.0
Ford High School         644.0
Griffin High School      625.0
Hernandez High School    652.0
Holden High School       581.0
Huang High School        655.0
Johnson High School      650.0
Pena High School         609.0
Rodriguez High School    637.0
Shelton High School      600.0
Thomas High School       638.0
Wilson High School       578.0
Wright High School       583.0
dtype: float64

In [47]:
# Calculate the math scores.
student_school_name = school_data_complete_df.set_index(["school_name"])["math_score"]
student_school_name

school_types = school_data_df.set_index(["school_name"])["type"]

In [48]:
# Calculate the average math scores.
per_school_averages = school_data_complete_df.groupby(["school_name"]).mean()
per_school_averages

,Student ID,reading_score,math_score,School ID,size,budget
school_name,,,,,,
Bailey High School,20358.5,81.033963,77.048432,7.0,4976.0,3124928.0
Cabrera High School,16941.5,83.975780,83.061895,6.0,1858.0,1081356.0
Figueroa High School,4391.0,81.158020,76.711767,1.0,2949.0,1884411.0
Ford High School,36165.0,80.746258,77.102592,13.0,2739.0,1763916.0
Griffin High School,12995.5,83.816757,83.351499,4.0,1468.0,917500.0
Hernandez High School,9944.0,80.934412,77.289752,3.0,4635.0,3022020.0
Holden High School,23060.0,83.814988,83.803279,8.0,427.0,248087.0
Huang High School,1458.0,81.182722,76.629414,0.0,2917.0,1910635.0
Johnson High School,32415.0,80.966394,77.072464,12.0,4761.0,3094650.0
Pena High School,23754.5,84.044699,83.839917,9.0,962.0,585858.0
Rodriguez High School,28035.0,80.744686,76.842711,11.0,3999.0,2547363.0
Shelton High School,6746.0,83.725724,83.359455,2.0,1761.0,1056600.0
Thomas High School,38352.0,83.848930,83.418349,14.0,1635.0,1043130.0
Wilson High School,14871.0,83.989488,83.274201,5.0,2283.0,1319574.0
Wright High School,25135.5,83.955000,83.682222,10.0,1800.0,1049400.0

In [49]:
# Calculate the average test scores.
per_school_math = school_data_complete_df.groupby(["school_name"]).mean()["math_score"]

per_school_reading = school_data_complete_df.groupby(["school_name"]).mean()["reading_score"]

In [50]:
# Calculate the passing scores by creating a filtered DataFrame.
per_school_passing_math  = school_data_complete_df[(school_data_complete_df["math_score"] >= 70)]

per_school_passing_reading  = school_data_complete_df[(school_data_complete_df["reading_score"] >= 70)]

In [51]:
per_school_passing_math = per_school_passing_math.groupby(["school_name"]).count()["student_name"]

per_school_passing_reading = per_school_passing_reading.groupby(["school_name"]).count()["student_name"]

# Calculate the percentage of passing math and reading scores per school.
per_school_passing_math = per_school_passing_math / per_school_counts * 100

per_school_passing_reading = per_school_passing_reading / per_school_counts * 100

# Calculate the overall passing percentage.
per_overall_passing_percentage = (per_school_passing_math + per_school_passing_reading) / 2

per_overall_passing_percentage = per_overall_passing_percentage.map("{:,.2f}".format)

In [52]:

# Adding a list of values with keys to create a new DataFrame.
#per_school_summary_df = pd.merge(school_types, per_school_counts, on=["school_name"])

#per_school_summary_df = pd.concat({
 #            "School Type": school_types,
  #           "Total Students": per_school_counts,
   #          "Total School Budget": per_school_budget,
    #         "Per Student Budget": per_school_capita,
     #        "Average Math Score": per_school_math,
      #     "Average Reading Score": per_school_reading,
       #    "% Passing Math": per_school_passing_math,
        #   "% Passing Reading": per_school_passing_reading,
         #  "% Overall Passing": per_overall_passing_percentage}, axis=1, sort=True)

per_school_summary_df = pd.DataFrame({
             "School Type": school_types,
             "Total Students": per_school_counts,
             "Total School Budget": per_school_budget,
             "Per Student Budget": per_school_capita,
             "Average Math Score": per_school_math,
           "Average Reading Score": per_school_reading,
           "% Passing Math": per_school_passing_math,
           "% Passing Reading": per_school_passing_reading,
           "% Overall Passing": per_overall_passing_percentage})

per_school_summary_df

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
Bailey High School,District,4976,3124928,628.0,77.048432,81.033963,66.680064,81.933280,74.31
Cabrera High School,Charter,1858,1081356,582.0,83.061895,83.975780,94.133477,97.039828,95.59
Figueroa High School,District,2949,1884411,639.0,76.711767,81.158020,65.988471,80.739234,73.36
Ford High School,District,2739,1763916,644.0,77.102592,80.746258,68.309602,79.299014,73.80
Griffin High School,Charter,1468,917500,625.0,83.351499,83.816757,93.392371,97.138965,95.27
Hernandez High School,District,4635,3022020,652.0,77.289752,80.934412,66.752967,80.862999,73.81
Holden High School,Charter,427,248087,581.0,83.803279,83.814988,92.505855,96.252927,94.38
Huang High School,District,2917,1910635,655.0,76.629414,81.182722,65.683922,81.316421,73.50
Johnson High School,District,4761,3094650,650.0,77.072464,80.966394,66.057551,81.222432,73.64
Pena High School,Charter,962,585858,609.0,83.839917,84.044699,94.594595,95.945946,95.27
Rodriguez High School,District,3999,2547363,637.0,76.842711,80.744686,66.366592,80.220055,73.29
Shelton High School,Charter,1761,1056600,600.0,83.359455,83.725724,93.867121,95.854628,94.86
Thomas High School,Charter,1635,1043130,638.0,83.418349,83.848930,93.272171,97.308869,95.29
Wilson High School,Charter,2283,1319574,578.0,83.274201,83.989488,93.867718,96.539641,95.20
Wright High School,Charter,1800,1049400,583.0,83.682222,83.955000,93.333333,96.611111,94.97

In [53]:

# Reorder the columns in the order you want them to appear.
new_column_order = ["School Type", "Total Students", "Total School Budget", "Per Student Budget", "Average Math Score", "Average Reading Score", "% Passing Math", "% Passing Reading", "% Overall Passing"]

# Assign district summary df the new column order.
per_school_summary_df = per_school_summary_df[new_column_order]

per_school_summary_df.head()

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
Bailey High School,District,4976,3124928,628.0,77.048432,81.033963,66.680064,81.933280,74.31
Cabrera High School,Charter,1858,1081356,582.0,83.061895,83.975780,94.133477,97.039828,95.59
Figueroa High School,District,2949,1884411,639.0,76.711767,81.158020,65.988471,80.739234,73.36
Ford High School,District,2739,1763916,644.0,77.102592,80.746258,68.309602,79.299014,73.80
Griffin High School,Charter,1468,917500,625.0,83.351499,83.816757,93.392371,97.138965,95.27

In [54]:
# Sort and show top five schools.
top_schools = per_school_summary_df.sort_values(["% Overall Passing"], ascending=False)

top_schools.head()

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
Cabrera High School,Charter,1858,1081356,582.0,83.061895,83.975780,94.133477,97.039828,95.59
Thomas High School,Charter,1635,1043130,638.0,83.418349,83.848930,93.272171,97.308869,95.29
Griffin High School,Charter,1468,917500,625.0,83.351499,83.816757,93.392371,97.138965,95.27
Pena High School,Charter,962,585858,609.0,83.839917,84.044699,94.594595,95.945946,95.27
Wilson High School,Charter,2283,1319574,578.0,83.274201,83.989488,93.867718,96.539641,95.20

In [55]:
# Sort and show top five schools.
bottom_schools = per_school_summary_df.sort_values(["% Overall Passing"], ascending=True)

bottom_schools.head()

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
Rodriguez High School,District,3999,2547363,637.0,76.842711,80.744686,66.366592,80.220055,73.29
Figueroa High School,District,2949,1884411,639.0,76.711767,81.158020,65.988471,80.739234,73.36
Huang High School,District,2917,1910635,655.0,76.629414,81.182722,65.683922,81.316421,73.50
Johnson High School,District,4761,3094650,650.0,77.072464,80.966394,66.057551,81.222432,73.64
Ford High School,District,2739,1763916,644.0,77.102592,80.746258,68.309602,79.299014,73.80

In [56]:
# Create a grade level DataFrames.
ninth_graders = school_data_complete_df[(school_data_complete_df["grade"] == "9th")]

tenth_graders = school_data_complete_df[(school_data_complete_df["grade"] == "10th")]

eleventh_graders = school_data_complete_df[(school_data_complete_df["grade"] == "11th")]

twelfth_graders = school_data_complete_df[(school_data_complete_df["grade"] == "12th")]

In [57]:
# Group each school Series by the school name for the average reading score.
ninth_grade_math_scores = ninth_graders.groupby(["school_name"]).mean()["math_score"]

tenth_grade_math_scores = tenth_graders.groupby(["school_name"]).mean()["math_score"]

eleventh_grade_math_scores = eleventh_graders.groupby(["school_name"]).mean()["math_score"]

twelfth_grade_math_scores = twelfth_graders.groupby(["school_name"]).mean()["math_score"]

In [58]:
# Combine each Series for average math scores by school into single DataFrame.
math_scores_by_grade = pd.DataFrame({
               "9th": ninth_grade_math_scores,
               "10th": tenth_grade_math_scores,
               "11th": eleventh_grade_math_scores,
               "12th": twelfth_grade_math_scores})

math_scores_by_grade.head()

                            9th       10th       11th       12th
school_name
Bailey High School    77.083676  76.996772  77.515588  76.492218
Cabrera High School   83.094697  83.154506  82.765560  83.277487
Figueroa High School  76.403037  76.539974  76.884344  77.151369
Ford High School      77.361345  77.672316  76.918058  76.179963
Griffin High School   82.044010  84.229064  83.842105  83.356164

In [59]:
# Format each grade column.
math_scores_by_grade["9th"] = math_scores_by_grade["9th"].map("{:.1f}".format)

math_scores_by_grade["10th"] = math_scores_by_grade["10th"].map("{:.1f}".format)

math_scores_by_grade["11th"] = math_scores_by_grade["11th"].map("{:.1f}".format)

math_scores_by_grade["12th"] = math_scores_by_grade["12th"].map("{:.1f}".format)

# Make sure the columns are in the correct order.
math_scores_by_grade = math_scores_by_grade[["9th", "10th", "11th", "12th"]]
# Remove the index name.
math_scores_by_grade.index.name = None# Display the DataFrame.
math_scores_by_grade.head()

                       9th  10th  11th  12th
Bailey High School    77.1  77.0  77.5  76.5
Cabrera High School   83.1  83.2  82.8  83.3
Figueroa High School  76.4  76.5  76.9  77.2
Ford High School      77.4  77.7  76.9  76.2
Griffin High School   82.0  84.2  83.8  83.4

In [60]:
# Group each school Series by the school name for the average reading score.
ninth_grade_reading_scores = ninth_graders.groupby(["school_name"]).mean()["reading_score"]

tenth_grade_reading_scores = tenth_graders.groupby(["school_name"]).mean()["reading_score"]

eleventh_grade_reading_scores = eleventh_graders.groupby(["school_name"]).mean()["reading_score"]

twelfth_grade_reading_scores = twelfth_graders.groupby(["school_name"]).mean()["reading_score"]

In [61]:
reading_scores_by_grade = pd.DataFrame({
               "9th": ninth_grade_reading_scores,
               "10th": tenth_grade_reading_scores,
               "11th": eleventh_grade_reading_scores,
               "12th": twelfth_grade_reading_scores})

reading_scores_by_grade.head()

                            9th       10th       11th       12th
school_name
Bailey High School    81.303155  80.907183  80.945643  80.912451
Cabrera High School   83.676136  84.253219  83.788382  84.287958
Figueroa High School  81.198598  81.408912  80.640339  81.384863
Ford High School      80.632653  81.262712  80.403642  80.662338
Griffin High School   83.369193  83.706897  84.288089  84.013699

In [62]:
# Format each grade column.
reading_scores_by_grade["9th"] = reading_scores_by_grade["9th"].map("{:,.1f}".format)

reading_scores_by_grade["10th"] = reading_scores_by_grade["10th"].map("{:,.1f}".format)

reading_scores_by_grade["11th"] = reading_scores_by_grade["11th"].map("{:,.1f}".format)

reading_scores_by_grade["12th"] = reading_scores_by_grade["12th"].map("{:,.1f}".format)

# Make sure the columns are in the correct order.
reading_scores_by_grade = reading_scores_by_grade[["9th", "10th", "11th", "12th"]]

# Remove the index name.
reading_scores_by_grade.index.name = None
# Display the data frame.
reading_scores_by_grade.head()

                       9th  10th  11th  12th
Bailey High School    81.3  80.9  80.9  80.9
Cabrera High School   83.7  84.3  83.8  84.3
Figueroa High School  81.2  81.4  80.6  81.4
Ford High School      80.6  81.3  80.4  80.7
Griffin High School   83.4  83.7  84.3  84.0

In [63]:
# Get the descriptive statistics for the per_school_capita.
per_school_capita.describe()

count     15.000000
mean     620.066667
std       28.544368
min      578.000000
25%      591.500000
50%      628.000000
75%      641.500000
max      655.000000
dtype: float64

In [64]:
# Establish the spending bins and group names.
spending_bins = [0, 585, 630, 645, 675]

group_names = ["<$584", "$585-629", "$630-644", "$645-675"]
per_school_capita.groupby(pd.cut(per_school_capita, spending_bins)).count()

(0, 585]      4
(585, 630]    4
(630, 645]    4
(645, 675]    3
dtype: int64

In [65]:

per_school_summary_df["Spending Ranges (Per Student)"] = pd.cut(per_school_capita, spending_bins, labels=group_names)

per_school_summary_df

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing,Spending Ranges (Per Student)
Bailey High School,District,4976,3124928,628.0,77.048432,81.033963,66.680064,81.933280,74.31,$585-629
Cabrera High School,Charter,1858,1081356,582.0,83.061895,83.975780,94.133477,97.039828,95.59,<$584
Figueroa High School,District,2949,1884411,639.0,76.711767,81.158020,65.988471,80.739234,73.36,$630-644
Ford High School,District,2739,1763916,644.0,77.102592,80.746258,68.309602,79.299014,73.80,$630-644
Griffin High School,Charter,1468,917500,625.0,83.351499,83.816757,93.392371,97.138965,95.27,$585-629
Hernandez High School,District,4635,3022020,652.0,77.289752,80.934412,66.752967,80.862999,73.81,$645-675
Holden High School,Charter,427,248087,581.0,83.803279,83.814988,92.505855,96.252927,94.38,<$584
Huang High School,District,2917,1910635,655.0,76.629414,81.182722,65.683922,81.316421,73.50,$645-675
Johnson High School,District,4761,3094650,650.0,77.072464,80.966394,66.057551,81.222432,73.64,$645-675
Pena High School,Charter,962,585858,609.0,83.839917,84.044699,94.594595,95.945946,95.27,$585-629
Rodriguez High School,District,3999,2547363,637.0,76.842711,80.744686,66.366592,80.220055,73.29,$630-644
Shelton High School,Charter,1761,1056600,600.0,83.359455,83.725724,93.867121,95.854628,94.86,$585-629
Thomas High School,Charter,1635,1043130,638.0,83.418349,83.848930,93.272171,97.308869,95.29,$630-644
Wilson High School,Charter,2283,1319574,578.0,83.274201,83.989488,93.867718,96.539641,95.20,<$584
Wright High School,Charter,1800,1049400,583.0,83.682222,83.955000,93.333333,96.611111,94.97,<$584

In [66]:
# Calculate averages for the desired columns.
spending_math_scores = per_school_summary_df.groupby(["Spending Ranges (Per Student)"]).mean()["Average Math Score"]

spending_reading_scores = per_school_summary_df.groupby(["Spending Ranges (Per Student)"]).mean()["Average Reading Score"]

spending_passing_math = per_school_summary_df.groupby(["Spending Ranges (Per Student)"]).mean()["% Passing Math"]

spending_passing_reading = per_school_summary_df.groupby(["Spending Ranges (Per Student)"]).mean()["% Passing Reading"]


# Calculate the overall passing percentage.
overall_passing_percentage = (spending_passing_math + spending_passing_reading) / 2

In [67]:
# Assemble into DataFrame.
spending_summary_df = pd.DataFrame({
          "Average Math Score" : spending_math_scores,
          "Average Reading Score": spending_reading_scores,
          "% Passing Math": spending_passing_math,
          "% Passing Reading": spending_passing_reading,
          "% Overall Passing": overall_passing_percentage})

spending_summary_df

,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
Spending Ranges (Per Student),,,,,
<$584,83.455399,83.933814,93.460096,96.610877,95.035486
$585-629,81.899826,83.155286,87.133538,92.718205,89.925871
$630-644,78.518855,81.624473,73.484209,84.391793,78.938001
$645-675,76.997210,81.027843,66.164813,81.133951,73.649382

In [68]:
# Formatting
spending_summary_df["Average Math Score"] = spending_summary_df["Average Math Score"].map("{:.1f}".format)

spending_summary_df["Average Reading Score"] = spending_summary_df["Average Reading Score"].map("{:.1f}".format)

spending_summary_df["% Passing Math"] = spending_summary_df["% Passing Math"].map("{:.0f}".format)

spending_summary_df["% Passing Reading"] = spending_summary_df["% Passing Reading"].map("{:.0f}".format)

spending_summary_df["% Overall Passing"] = spending_summary_df["% Overall Passing"].map("{:.0f}".format)

spending_summary_df

,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
Spending Ranges (Per Student),,,,,
<$584,83.5,83.9,93,97,95
$585-629,81.9,83.2,87,93,90
$630-644,78.5,81.6,73,84,79
$645-675,77.0,81.0,66,81,74

In [69]:
# Categorize spending based on the bins.

per_school_summary_df["Spending Ranges (Per Student)"] = pd.cut(per_school_capita, spending_bins, labels=group_names)

per_school_summary_df

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing,Spending Ranges (Per Student)
Bailey High School,District,4976,3124928,628.0,77.048432,81.033963,66.680064,81.933280,74.31,$585-629
Cabrera High School,Charter,1858,1081356,582.0,83.061895,83.975780,94.133477,97.039828,95.59,<$584
Figueroa High School,District,2949,1884411,639.0,76.711767,81.158020,65.988471,80.739234,73.36,$630-644
Ford High School,District,2739,1763916,644.0,77.102592,80.746258,68.309602,79.299014,73.80,$630-644
Griffin High School,Charter,1468,917500,625.0,83.351499,83.816757,93.392371,97.138965,95.27,$585-629
Hernandez High School,District,4635,3022020,652.0,77.289752,80.934412,66.752967,80.862999,73.81,$645-675
Holden High School,Charter,427,248087,581.0,83.803279,83.814988,92.505855,96.252927,94.38,<$584
Huang High School,District,2917,1910635,655.0,76.629414,81.182722,65.683922,81.316421,73.50,$645-675
Johnson High School,District,4761,3094650,650.0,77.072464,80.966394,66.057551,81.222432,73.64,$645-675
Pena High School,Charter,962,585858,609.0,83.839917,84.044699,94.594595,95.945946,95.27,$585-629
Rodriguez High School,District,3999,2547363,637.0,76.842711,80.744686,66.366592,80.220055,73.29,$630-644
Shelton High School,Charter,1761,1056600,600.0,83.359455,83.725724,93.867121,95.854628,94.86,$585-629
Thomas High School,Charter,1635,1043130,638.0,83.418349,83.848930,93.272171,97.308869,95.29,$630-644
Wilson High School,Charter,2283,1319574,578.0,83.274201,83.989488,93.867718,96.539641,95.20,<$584
Wright High School,Charter,1800,1049400,583.0,83.682222,83.955000,93.333333,96.611111,94.97,<$584

In [70]:
size_bins = [0, 1000, 2000, 5000]

group_names = ["Small (<1000)", "Medium (1000-2000)", "Large (2000-5000)"]

per_school_summary_df["School Size"] = pd.cut(per_school_summary_df["Total Students"], size_bins, labels=group_names)

per_school_summary_df.head()

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing,Spending Ranges (Per Student),School Size
Bailey High School,District,4976,3124928,628.0,77.048432,81.033963,66.680064,81.933280,74.31,$585-629,Large (2000-5000)
Cabrera High School,Charter,1858,1081356,582.0,83.061895,83.975780,94.133477,97.039828,95.59,<$584,Medium (1000-2000)
Figueroa High School,District,2949,1884411,639.0,76.711767,81.158020,65.988471,80.739234,73.36,$630-644,Large (2000-5000)
Ford High School,District,2739,1763916,644.0,77.102592,80.746258,68.309602,79.299014,73.80,$630-644,Large (2000-5000)
Griffin High School,Charter,1468,917500,625.0,83.351499,83.816757,93.392371,97.138965,95.27,$585-629,Medium (1000-2000)

In [71]:
size_math_scores = per_school_summary_df.groupby(["School Size"]).mean()["Average Math Score"]

size_reading_scores = per_school_summary_df.groupby(["School Size"]).mean()["Average Reading Score"]

size_passing_math = per_school_summary_df.groupby(["School Size"]).mean()["% Passing Math"]

size_passing_reading = per_school_summary_df.groupby(["School Size"]).mean()["% Passing Reading"]

size_overall_passing = (size_passing_math + size_passing_reading) / 2

size_summary_df = pd.DataFrame({
          "Average Math Score" : size_math_scores,
          "Average Reading Score": size_reading_scores,
          "% Passing Math": size_passing_math,
          "% Passing Reading": size_passing_reading,
          "% Overall Passing": size_overall_passing})

size_summary_df

,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
School Size,,,,,
Small (<1000),83.821598,83.929843,93.550225,96.099437,94.824831
Medium (1000-2000),83.374684,83.864438,93.599695,96.790680,95.195187
Large (2000-5000),77.746417,81.344493,69.963361,82.766634,76.364998

In [72]:
# Calculate averages for the desired columns. 
type_math_scores = per_school_summary_df.groupby(["School Type"]).mean()["Average Math Score"]

type_reading_scores = per_school_summary_df.groupby(["School Type"]).mean()["Average Reading Score"]

type_passing_math = per_school_summary_df.groupby(["School Type"]).mean()["% Passing Math"]

type_passing_reading = per_school_summary_df.groupby(["School Type"]).mean()["% Passing Reading"]

type_overall_passing = (type_passing_math + type_passing_reading) / 2

In [73]:
# Assemble into DataFrame.
type_summary_df = pd.DataFrame({
          "Average Math Score" : type_math_scores,
          "Average Reading Score": type_reading_scores,
          "% Passing Math": type_passing_math,
          "% Passing Reading": type_passing_reading,
          "% Overall Passing": type_overall_passing})

type_summary_df

,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
School Type,,,,,
Charter,83.473852,83.896421,93.620830,96.586489,95.103660
District,76.956733,80.966636,66.548453,80.799062,73.673757

In [74]:
# Formatting
type_summary_df["Average Math Score"] = type_summary_df["Average Math Score"].map("{:.1f}".format)

type_summary_df["Average Reading Score"] = type_summary_df["Average Reading Score"].map("{:.1f}".format)

type_summary_df["% Passing Math"] = type_summary_df["% Passing Math"].map("{:.0f}".format)

type_summary_df["% Passing Reading"] = type_summary_df["% Passing Reading"].map("{:.0f}".format)

type_summary_df["% Overall Passing"] = type_summary_df["% Overall Passing"].map("{:.0f}".format)

type_summary_df

,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
School Type,,,,,
Charter,83.5,83.9,94,97,95
District,77.0,81.0,67,81,74